// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/backfill.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackfillClient is the client API for Backfill service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackfillClient interface {
	BackfillPullRequestLinks(ctx context.Context, in *BackfillPullRequestLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BackfillParticipantsBandwidth(ctx context.Context, in *BackfillParticipantsBandwidthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type backfillClient struct {
	cc grpc.ClientConnInterface
}

func NewBackfillClient(cc grpc.ClientConnInterface) BackfillClient {
	return &backfillClient{cc}
}

func (c *backfillClient) BackfillPullRequestLinks(ctx context.Context, in *BackfillPullRequestLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Backfill/BackfillPullRequestLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backfillClient) BackfillParticipantsBandwidth(ctx context.Context, in *BackfillParticipantsBandwidthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Backfill/BackfillParticipantsBandwidth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackfillServer is the server API for Backfill service.
// All implementations must embed UnimplementedBackfillServer
// for forward compatibility
type BackfillServer interface {
	BackfillPullRequestLinks(context.Context, *BackfillPullRequestLinksRequest) (*emptypb.Empty, error)
	BackfillParticipantsBandwidth(context.Context, *BackfillParticipantsBandwidthRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBackfillServer()
}

// UnimplementedBackfillServer must be embedded to have forward compatible implementations.
type UnimplementedBackfillServer struct {
}

func (UnimplementedBackfillServer) BackfillPullRequestLinks(context.Context, *BackfillPullRequestLinksRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackfillPullRequestLinks not implemented")
}
func (UnimplementedBackfillServer) BackfillParticipantsBandwidth(context.Context, *BackfillParticipantsBandwidthRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackfillParticipantsBandwidth not implemented")
}
func (UnimplementedBackfillServer) mustEmbedUnimplementedBackfillServer() {}

// UnsafeBackfillServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackfillServer will
// result in compilation errors.
type UnsafeBackfillServer interface {
	mustEmbedUnimplementedBackfillServer()
}

func RegisterBackfillServer(s grpc.ServiceRegistrar, srv BackfillServer) {
	s.RegisterService(&Backfill_ServiceDesc, srv)
}

func _Backfill_BackfillPullRequestLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackfillPullRequestLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackfillServer).BackfillPullRequestLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Backfill/BackfillPullRequestLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackfillServer).BackfillPullRequestLinks(ctx, req.(*BackfillPullRequestLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backfill_BackfillParticipantsBandwidth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackfillParticipantsBandwidthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackfillServer).BackfillParticipantsBandwidth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Backfill/BackfillParticipantsBandwidth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackfillServer).BackfillParticipantsBandwidth(ctx, req.(*BackfillParticipantsBandwidthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Backfill_ServiceDesc is the grpc.ServiceDesc for Backfill service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backfill_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Backfill",
	HandlerType: (*BackfillServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BackfillPullRequestLinks",
			Handler:    _Backfill_BackfillPullRequestLinks_Handler,
		},
		{
			MethodName: "BackfillParticipantsBandwidth",
			Handler:    _Backfill_BackfillParticipantsBandwidth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/backfill.proto",
}
