// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: core/api/proto/backfill.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackFillClient is the client API for BackFill service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackFillClient interface {
	BackFillPullRequestLinks(ctx context.Context, in *BackFillPullRequestLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BackFillParticipantsBandwidth(ctx context.Context, in *BackFillParticipantsBandwidthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type backFillClient struct {
	cc grpc.ClientConnInterface
}

func NewBackFillClient(cc grpc.ClientConnInterface) BackFillClient {
	return &backFillClient{cc}
}

func (c *backFillClient) BackFillPullRequestLinks(ctx context.Context, in *BackFillPullRequestLinksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/BackFill/BackFillPullRequestLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backFillClient) BackFillParticipantsBandwidth(ctx context.Context, in *BackFillParticipantsBandwidthRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/BackFill/BackFillParticipantsBandwidth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackFillServer is the server API for BackFill service.
// All implementations must embed UnimplementedBackFillServer
// for forward compatibility
type BackFillServer interface {
	BackFillPullRequestLinks(context.Context, *BackFillPullRequestLinksRequest) (*emptypb.Empty, error)
	BackFillParticipantsBandwidth(context.Context, *BackFillParticipantsBandwidthRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBackFillServer()
}

// UnimplementedBackFillServer must be embedded to have forward compatible implementations.
type UnimplementedBackFillServer struct {
}

func (UnimplementedBackFillServer) BackFillPullRequestLinks(context.Context, *BackFillPullRequestLinksRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackFillPullRequestLinks not implemented")
}
func (UnimplementedBackFillServer) BackFillParticipantsBandwidth(context.Context, *BackFillParticipantsBandwidthRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackFillParticipantsBandwidth not implemented")
}
func (UnimplementedBackFillServer) mustEmbedUnimplementedBackFillServer() {}

// UnsafeBackFillServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackFillServer will
// result in compilation errors.
type UnsafeBackFillServer interface {
	mustEmbedUnimplementedBackFillServer()
}

func RegisterBackFillServer(s grpc.ServiceRegistrar, srv BackFillServer) {
	s.RegisterService(&BackFill_ServiceDesc, srv)
}

func _BackFill_BackFillPullRequestLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackFillPullRequestLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackFillServer).BackFillPullRequestLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackFill/BackFillPullRequestLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackFillServer).BackFillPullRequestLinks(ctx, req.(*BackFillPullRequestLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackFill_BackFillParticipantsBandwidth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackFillParticipantsBandwidthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackFillServer).BackFillParticipantsBandwidth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackFill/BackFillParticipantsBandwidth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackFillServer).BackFillParticipantsBandwidth(ctx, req.(*BackFillParticipantsBandwidthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackFill_ServiceDesc is the grpc.ServiceDesc for BackFill service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackFill_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BackFill",
	HandlerType: (*BackFillServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BackFillPullRequestLinks",
			Handler:    _BackFill_BackFillPullRequestLinks_Handler,
		},
		{
			MethodName: "BackFillParticipantsBandwidth",
			Handler:    _BackFill_BackFillParticipantsBandwidth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/api/proto/backfill.proto",
}
