// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: core/api/proto/sprint.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActiveSprintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId uint64 `protobuf:"varint,1,opt,name=teamId,proto3" json:"teamId,omitempty"`
}

func (x *GetActiveSprintRequest) Reset() {
	*x = GetActiveSprintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_proto_sprint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSprintRequest) ProtoMessage() {}

func (x *GetActiveSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_proto_sprint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSprintRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSprintRequest) Descriptor() ([]byte, []int) {
	return file_core_api_proto_sprint_proto_rawDescGZIP(), []int{0}
}

func (x *GetActiveSprintRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type SprintMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=endAt,proto3" json:"endAt,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	OwningTeamId uint64                 `protobuf:"varint,5,opt,name=owningTeamId,proto3" json:"owningTeamId,omitempty"`
}

func (x *SprintMsg) Reset() {
	*x = SprintMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_proto_sprint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SprintMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprintMsg) ProtoMessage() {}

func (x *SprintMsg) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_proto_sprint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprintMsg.ProtoReflect.Descriptor instead.
func (*SprintMsg) Descriptor() ([]byte, []int) {
	return file_core_api_proto_sprint_proto_rawDescGZIP(), []int{1}
}

func (x *SprintMsg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SprintMsg) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *SprintMsg) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *SprintMsg) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SprintMsg) GetOwningTeamId() uint64 {
	if x != nil {
		return x.OwningTeamId
	}
	return 0
}

type AddTaskToSprintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   uint64 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	SprintId uint64 `protobuf:"varint,2,opt,name=sprintId,proto3" json:"sprintId,omitempty"`
}

func (x *AddTaskToSprintRequest) Reset() {
	*x = AddTaskToSprintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_proto_sprint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTaskToSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskToSprintRequest) ProtoMessage() {}

func (x *AddTaskToSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_proto_sprint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskToSprintRequest.ProtoReflect.Descriptor instead.
func (*AddTaskToSprintRequest) Descriptor() ([]byte, []int) {
	return file_core_api_proto_sprint_proto_rawDescGZIP(), []int{2}
}

func (x *AddTaskToSprintRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *AddTaskToSprintRequest) GetSprintId() uint64 {
	if x != nil {
		return x.SprintId
	}
	return 0
}

var File_core_api_proto_sprint_proto protoreflect.FileDescriptor

var file_core_api_proto_sprint_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0xe1, 0x01,
	0x0a, 0x09, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41,
	0x74, 0x12, 0x30, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x65, 0x6e,
	0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x6f, 0x77, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x22, 0x4c, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x6f, 0x53, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x32,
	0x84, 0x01, 0x0a, 0x06, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x17, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x4d,
	0x73, 0x67, 0x12, 0x42, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x6f, 0x53,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x54,
	0x6f, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x79, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_api_proto_sprint_proto_rawDescOnce sync.Once
	file_core_api_proto_sprint_proto_rawDescData = file_core_api_proto_sprint_proto_rawDesc
)

func file_core_api_proto_sprint_proto_rawDescGZIP() []byte {
	file_core_api_proto_sprint_proto_rawDescOnce.Do(func() {
		file_core_api_proto_sprint_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_proto_sprint_proto_rawDescData)
	})
	return file_core_api_proto_sprint_proto_rawDescData
}

var file_core_api_proto_sprint_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_api_proto_sprint_proto_goTypes = []interface{}{
	(*GetActiveSprintRequest)(nil), // 0: GetActiveSprintRequest
	(*SprintMsg)(nil),              // 1: SprintMsg
	(*AddTaskToSprintRequest)(nil), // 2: AddTaskToSprintRequest
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 4: google.protobuf.Empty
}
var file_core_api_proto_sprint_proto_depIdxs = []int32{
	3, // 0: SprintMsg.startAt:type_name -> google.protobuf.Timestamp
	3, // 1: SprintMsg.endAt:type_name -> google.protobuf.Timestamp
	3, // 2: SprintMsg.createdAt:type_name -> google.protobuf.Timestamp
	0, // 3: Sprint.GetActiveSprint:input_type -> GetActiveSprintRequest
	2, // 4: Sprint.AddTaskToSprint:input_type -> AddTaskToSprintRequest
	1, // 5: Sprint.GetActiveSprint:output_type -> SprintMsg
	4, // 6: Sprint.AddTaskToSprint:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_api_proto_sprint_proto_init() }
func file_core_api_proto_sprint_proto_init() {
	if File_core_api_proto_sprint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_api_proto_sprint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveSprintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_proto_sprint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SprintMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_proto_sprint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTaskToSprintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_proto_sprint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_api_proto_sprint_proto_goTypes,
		DependencyIndexes: file_core_api_proto_sprint_proto_depIdxs,
		MessageInfos:      file_core_api_proto_sprint_proto_msgTypes,
	}.Build()
	File_core_api_proto_sprint_proto = out.File
	file_core_api_proto_sprint_proto_rawDesc = nil
	file_core_api_proto_sprint_proto_goTypes = nil
	file_core_api_proto_sprint_proto_depIdxs = nil
}
