// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: core/api/proto/story.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StoryClient is the client API for Story service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoryClient interface {
	GetStory(ctx context.Context, in *GetStoryRequest, opts ...grpc.CallOption) (*StoryMsg, error)
	GetAwaitForStories(ctx context.Context, in *GetAwaitForStoriesRequest, opts ...grpc.CallOption) (*GetAwaitForStoriesResponse, error)
	CreateStory(ctx context.Context, in *CreateStoryRequest, opts ...grpc.CallOption) (*CreateStoryResponse, error)
	UpdateStory(ctx context.Context, in *UpdateStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteStory(ctx context.Context, in *DeleteStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MoveStoryToUpcoming(ctx context.Context, in *MoveStoryToUpcomingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MoveStoryToInProgress(ctx context.Context, in *MoveStoryToInProgressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MoveStoryToDelivered(ctx context.Context, in *MoveStoryToDeliveredRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MoveStoryToBlocked(ctx context.Context, in *MoveStoryToBlockedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddAwaitForStory(ctx context.Context, in *AddAwaitForStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveAwaitForStory(ctx context.Context, in *RemoveAwaitForStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddTaskToStory(ctx context.Context, in *AddTaskToStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveTaskFromStory(ctx context.Context, in *RemoveTaskFromStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type storyClient struct {
	cc grpc.ClientConnInterface
}

func NewStoryClient(cc grpc.ClientConnInterface) StoryClient {
	return &storyClient{cc}
}

func (c *storyClient) GetStory(ctx context.Context, in *GetStoryRequest, opts ...grpc.CallOption) (*StoryMsg, error) {
	out := new(StoryMsg)
	err := c.cc.Invoke(ctx, "/Story/GetStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) GetAwaitForStories(ctx context.Context, in *GetAwaitForStoriesRequest, opts ...grpc.CallOption) (*GetAwaitForStoriesResponse, error) {
	out := new(GetAwaitForStoriesResponse)
	err := c.cc.Invoke(ctx, "/Story/GetAwaitForStories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) CreateStory(ctx context.Context, in *CreateStoryRequest, opts ...grpc.CallOption) (*CreateStoryResponse, error) {
	out := new(CreateStoryResponse)
	err := c.cc.Invoke(ctx, "/Story/CreateStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) UpdateStory(ctx context.Context, in *UpdateStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/UpdateStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) DeleteStory(ctx context.Context, in *DeleteStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/DeleteStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) MoveStoryToUpcoming(ctx context.Context, in *MoveStoryToUpcomingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/MoveStoryToUpcoming", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) MoveStoryToInProgress(ctx context.Context, in *MoveStoryToInProgressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/MoveStoryToInProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) MoveStoryToDelivered(ctx context.Context, in *MoveStoryToDeliveredRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/MoveStoryToDelivered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) MoveStoryToBlocked(ctx context.Context, in *MoveStoryToBlockedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/MoveStoryToBlocked", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) AddAwaitForStory(ctx context.Context, in *AddAwaitForStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/AddAwaitForStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) RemoveAwaitForStory(ctx context.Context, in *RemoveAwaitForStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/RemoveAwaitForStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) AddTaskToStory(ctx context.Context, in *AddTaskToStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/AddTaskToStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyClient) RemoveTaskFromStory(ctx context.Context, in *RemoveTaskFromStoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Story/RemoveTaskFromStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoryServer is the server API for Story service.
// All implementations must embed UnimplementedStoryServer
// for forward compatibility
type StoryServer interface {
	GetStory(context.Context, *GetStoryRequest) (*StoryMsg, error)
	GetAwaitForStories(context.Context, *GetAwaitForStoriesRequest) (*GetAwaitForStoriesResponse, error)
	CreateStory(context.Context, *CreateStoryRequest) (*CreateStoryResponse, error)
	UpdateStory(context.Context, *UpdateStoryRequest) (*emptypb.Empty, error)
	DeleteStory(context.Context, *DeleteStoryRequest) (*emptypb.Empty, error)
	MoveStoryToUpcoming(context.Context, *MoveStoryToUpcomingRequest) (*emptypb.Empty, error)
	MoveStoryToInProgress(context.Context, *MoveStoryToInProgressRequest) (*emptypb.Empty, error)
	MoveStoryToDelivered(context.Context, *MoveStoryToDeliveredRequest) (*emptypb.Empty, error)
	MoveStoryToBlocked(context.Context, *MoveStoryToBlockedRequest) (*emptypb.Empty, error)
	AddAwaitForStory(context.Context, *AddAwaitForStoryRequest) (*emptypb.Empty, error)
	RemoveAwaitForStory(context.Context, *RemoveAwaitForStoryRequest) (*emptypb.Empty, error)
	AddTaskToStory(context.Context, *AddTaskToStoryRequest) (*emptypb.Empty, error)
	RemoveTaskFromStory(context.Context, *RemoveTaskFromStoryRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedStoryServer()
}

// UnimplementedStoryServer must be embedded to have forward compatible implementations.
type UnimplementedStoryServer struct {
}

func (UnimplementedStoryServer) GetStory(context.Context, *GetStoryRequest) (*StoryMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStory not implemented")
}
func (UnimplementedStoryServer) GetAwaitForStories(context.Context, *GetAwaitForStoriesRequest) (*GetAwaitForStoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAwaitForStories not implemented")
}
func (UnimplementedStoryServer) CreateStory(context.Context, *CreateStoryRequest) (*CreateStoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStory not implemented")
}
func (UnimplementedStoryServer) UpdateStory(context.Context, *UpdateStoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStory not implemented")
}
func (UnimplementedStoryServer) DeleteStory(context.Context, *DeleteStoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStory not implemented")
}
func (UnimplementedStoryServer) MoveStoryToUpcoming(context.Context, *MoveStoryToUpcomingRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveStoryToUpcoming not implemented")
}
func (UnimplementedStoryServer) MoveStoryToInProgress(context.Context, *MoveStoryToInProgressRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveStoryToInProgress not implemented")
}
func (UnimplementedStoryServer) MoveStoryToDelivered(context.Context, *MoveStoryToDeliveredRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveStoryToDelivered not implemented")
}
func (UnimplementedStoryServer) MoveStoryToBlocked(context.Context, *MoveStoryToBlockedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveStoryToBlocked not implemented")
}
func (UnimplementedStoryServer) AddAwaitForStory(context.Context, *AddAwaitForStoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAwaitForStory not implemented")
}
func (UnimplementedStoryServer) RemoveAwaitForStory(context.Context, *RemoveAwaitForStoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAwaitForStory not implemented")
}
func (UnimplementedStoryServer) AddTaskToStory(context.Context, *AddTaskToStoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTaskToStory not implemented")
}
func (UnimplementedStoryServer) RemoveTaskFromStory(context.Context, *RemoveTaskFromStoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTaskFromStory not implemented")
}
func (UnimplementedStoryServer) mustEmbedUnimplementedStoryServer() {}

// UnsafeStoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoryServer will
// result in compilation errors.
type UnsafeStoryServer interface {
	mustEmbedUnimplementedStoryServer()
}

func RegisterStoryServer(s grpc.ServiceRegistrar, srv StoryServer) {
	s.RegisterService(&Story_ServiceDesc, srv)
}

func _Story_GetStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).GetStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/GetStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).GetStory(ctx, req.(*GetStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_GetAwaitForStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAwaitForStoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).GetAwaitForStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/GetAwaitForStories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).GetAwaitForStories(ctx, req.(*GetAwaitForStoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_CreateStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).CreateStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/CreateStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).CreateStory(ctx, req.(*CreateStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_UpdateStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).UpdateStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/UpdateStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).UpdateStory(ctx, req.(*UpdateStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_DeleteStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).DeleteStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/DeleteStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).DeleteStory(ctx, req.(*DeleteStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_MoveStoryToUpcoming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveStoryToUpcomingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).MoveStoryToUpcoming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/MoveStoryToUpcoming",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).MoveStoryToUpcoming(ctx, req.(*MoveStoryToUpcomingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_MoveStoryToInProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveStoryToInProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).MoveStoryToInProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/MoveStoryToInProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).MoveStoryToInProgress(ctx, req.(*MoveStoryToInProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_MoveStoryToDelivered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveStoryToDeliveredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).MoveStoryToDelivered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/MoveStoryToDelivered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).MoveStoryToDelivered(ctx, req.(*MoveStoryToDeliveredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_MoveStoryToBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveStoryToBlockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).MoveStoryToBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/MoveStoryToBlocked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).MoveStoryToBlocked(ctx, req.(*MoveStoryToBlockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_AddAwaitForStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAwaitForStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).AddAwaitForStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/AddAwaitForStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).AddAwaitForStory(ctx, req.(*AddAwaitForStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_RemoveAwaitForStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAwaitForStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).RemoveAwaitForStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/RemoveAwaitForStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).RemoveAwaitForStory(ctx, req.(*RemoveAwaitForStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_AddTaskToStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskToStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).AddTaskToStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/AddTaskToStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).AddTaskToStory(ctx, req.(*AddTaskToStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Story_RemoveTaskFromStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTaskFromStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServer).RemoveTaskFromStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Story/RemoveTaskFromStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServer).RemoveTaskFromStory(ctx, req.(*RemoveTaskFromStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Story_ServiceDesc is the grpc.ServiceDesc for Story service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Story_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Story",
	HandlerType: (*StoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStory",
			Handler:    _Story_GetStory_Handler,
		},
		{
			MethodName: "GetAwaitForStories",
			Handler:    _Story_GetAwaitForStories_Handler,
		},
		{
			MethodName: "CreateStory",
			Handler:    _Story_CreateStory_Handler,
		},
		{
			MethodName: "UpdateStory",
			Handler:    _Story_UpdateStory_Handler,
		},
		{
			MethodName: "DeleteStory",
			Handler:    _Story_DeleteStory_Handler,
		},
		{
			MethodName: "MoveStoryToUpcoming",
			Handler:    _Story_MoveStoryToUpcoming_Handler,
		},
		{
			MethodName: "MoveStoryToInProgress",
			Handler:    _Story_MoveStoryToInProgress_Handler,
		},
		{
			MethodName: "MoveStoryToDelivered",
			Handler:    _Story_MoveStoryToDelivered_Handler,
		},
		{
			MethodName: "MoveStoryToBlocked",
			Handler:    _Story_MoveStoryToBlocked_Handler,
		},
		{
			MethodName: "AddAwaitForStory",
			Handler:    _Story_AddAwaitForStory_Handler,
		},
		{
			MethodName: "RemoveAwaitForStory",
			Handler:    _Story_RemoveAwaitForStory_Handler,
		},
		{
			MethodName: "AddTaskToStory",
			Handler:    _Story_AddTaskToStory_Handler,
		},
		{
			MethodName: "RemoveTaskFromStory",
			Handler:    _Story_RemoveTaskFromStory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/api/proto/story.proto",
}
