// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: core/api/proto/task_link.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId       uint64  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Title        string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url          string  `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	IconUrl      *string `protobuf:"bytes,4,opt,name=iconUrl,proto3,oneof" json:"iconUrl,omitempty"`
	IconHoverUrl *string `protobuf:"bytes,5,opt,name=iconHoverUrl,proto3,oneof" json:"iconHoverUrl,omitempty"`
	PreviewTitle string  `protobuf:"bytes,6,opt,name=preview_title,json=previewTitle,proto3" json:"preview_title,omitempty"`
}

func (x *CreateTaskLinkRequest) Reset() {
	*x = CreateTaskLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_proto_task_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskLinkRequest) ProtoMessage() {}

func (x *CreateTaskLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_proto_task_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskLinkRequest) Descriptor() ([]byte, []int) {
	return file_core_api_proto_task_link_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskLinkRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateTaskLinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateTaskLinkRequest) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *CreateTaskLinkRequest) GetIconHoverUrl() string {
	if x != nil && x.IconHoverUrl != nil {
		return *x.IconHoverUrl
	}
	return ""
}

func (x *CreateTaskLinkRequest) GetPreviewTitle() string {
	if x != nil {
		return x.PreviewTitle
	}
	return ""
}

type CreateTaskLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkId uint64 `protobuf:"varint,1,opt,name=linkId,proto3" json:"linkId,omitempty"`
}

func (x *CreateTaskLinkResponse) Reset() {
	*x = CreateTaskLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_proto_task_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskLinkResponse) ProtoMessage() {}

func (x *CreateTaskLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_proto_task_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskLinkResponse) Descriptor() ([]byte, []int) {
	return file_core_api_proto_task_link_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskLinkResponse) GetLinkId() uint64 {
	if x != nil {
		return x.LinkId
	}
	return 0
}

type DeleteTaskLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkId uint64 `protobuf:"varint,1,opt,name=linkId,proto3" json:"linkId,omitempty"`
}

func (x *DeleteTaskLinkRequest) Reset() {
	*x = DeleteTaskLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_proto_task_link_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskLinkRequest) ProtoMessage() {}

func (x *DeleteTaskLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_proto_task_link_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskLinkRequest) Descriptor() ([]byte, []int) {
	return file_core_api_proto_task_link_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTaskLinkRequest) GetLinkId() uint64 {
	if x != nil {
		return x.LinkId
	}
	return 0
}

var File_core_api_proto_task_link_proto protoreflect.FileDescriptor

var file_core_api_proto_task_link_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x01,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e,
	0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x69, 0x63, 0x6f, 0x6e, 0x48, 0x6f,
	0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0c,
	0x69, 0x63, 0x6f, 0x6e, 0x48, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12,
	0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c,
	0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x48, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72,
	0x6c, 0x22, 0x30, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x69, 0x6e, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x69, 0x6e,
	0x6b, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x69,
	0x6e, 0x6b, 0x49, 0x64, 0x32, 0x8f, 0x01, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x6e,
	0x6b, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4c,
	0x69, 0x6e, 0x6b, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x79, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_api_proto_task_link_proto_rawDescOnce sync.Once
	file_core_api_proto_task_link_proto_rawDescData = file_core_api_proto_task_link_proto_rawDesc
)

func file_core_api_proto_task_link_proto_rawDescGZIP() []byte {
	file_core_api_proto_task_link_proto_rawDescOnce.Do(func() {
		file_core_api_proto_task_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_proto_task_link_proto_rawDescData)
	})
	return file_core_api_proto_task_link_proto_rawDescData
}

var file_core_api_proto_task_link_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_api_proto_task_link_proto_goTypes = []interface{}{
	(*CreateTaskLinkRequest)(nil),  // 0: CreateTaskLinkRequest
	(*CreateTaskLinkResponse)(nil), // 1: CreateTaskLinkResponse
	(*DeleteTaskLinkRequest)(nil),  // 2: DeleteTaskLinkRequest
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_core_api_proto_task_link_proto_depIdxs = []int32{
	0, // 0: TaskLink.CreateTaskLink:input_type -> CreateTaskLinkRequest
	2, // 1: TaskLink.DeleteTaskLink:input_type -> DeleteTaskLinkRequest
	1, // 2: TaskLink.CreateTaskLink:output_type -> CreateTaskLinkResponse
	3, // 3: TaskLink.DeleteTaskLink:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_api_proto_task_link_proto_init() }
func file_core_api_proto_task_link_proto_init() {
	if File_core_api_proto_task_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_api_proto_task_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_proto_task_link_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_proto_task_link_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_api_proto_task_link_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_proto_task_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_api_proto_task_link_proto_goTypes,
		DependencyIndexes: file_core_api_proto_task_link_proto_depIdxs,
		MessageInfos:      file_core_api_proto_task_link_proto_msgTypes,
	}.Build()
	File_core_api_proto_task_link_proto = out.File
	file_core_api_proto_task_link_proto_rawDesc = nil
	file_core_api_proto_task_link_proto_goTypes = nil
	file_core_api_proto_task_link_proto_depIdxs = nil
}
