package daotest

const AppTableName = "app"
const AppTeamInstallationTableName = "appTeamInstallation"
const AppVersionTableName = "appVersion"
const AppVersionVisibleTeamTableName = "appVersionVisibleTeam"
const InvitationTableName = "invitation"
const MessageTableName = "message"
const SprintTableName = "sprint"
const SprintParticipantTableName = "sprintParticipant"
const SprintTaskRelationTableName = "sprintTaskRelation"
const StoryTaskRelationTableName = "storyTaskRelation"
const TaskTableName = "task"
const TaskAwaitForRelationTableName = "taskAwaitForRelation"
const TaskLinkTableName = "taskLink"
const TeamTableName = "team"
const TeamFileUploadSessionTableName = "teamFileUploadSession"
const TeamMemberTableName = "teamMember"
const TeamMemberGroupTableName = "teamMemberGroup"
const TeamMemberGroupUserRelationTableName = "teamMemberGroupUserRelation"
const ThreadTableName = "thread"
const UserTableName = "user"
const UserFileUploadSessionTableName = "userFileUploadSession"
const AppPackageUploadSessionTableName = "appPackageUploadSession"
const TaskFileUploadSessionTableName = "taskFileUploadSession"
const AttachmentListTableName = "attachmentList"
const ImageTableName = "image"
