package daotest

const UserTableName = "user"
const TeamTableName = "team"
const TeamMemberTableName = "teamMember"
const TaskTableName = "task"
const TaskLinkTableName = "taskLink"
const TaskAwaitForRelationTableName = "taskAwaitForRelation"
const SprintTableName = "sprint"
const SprintParticipantTableName = "sprintParticipant"
const SprintTaskRelationTableName = "sprintTaskRelation"
const InvitationName = "invitation"
const MessageTableName = "message"
const ThreadTableName = "thread"
const UserFileUploadSessionTableName = "userFileUploadSession"
const TeamFileUploadSessionTableName = "teamFileUploadSession"
const AppTableName = "app"
const AppVersionTableName = "appVersion"
const AppVersionVisibleTeamTableName = "appVersionVisibleTeam"
const AppTeamInstallationTableName = "appTeamInstallation"
