schema {
    query: Query
    mutation: Mutation
}

type Query {
    needAttentionTask: Task
    upcomingTasks: [Task!]!
    deliveredTasks: [Task!]!
    task(taskId: ID!): Task
}

type Mutation {
    createTask(task: TaskInput!): ID!
    deleteTask(taskId: ID!): Void
    updateTask(taskId: ID!, task: TaskInput!): Void
    performTaskAction(taskId: ID!, action: TaskAction!): Void
}

input TaskInput {
    goal: String
    dueAt: Date
    context: String
    ownerUserID: ID
    numOfUnknowns: Int
    domainExpertUserIDs: [ID!]!
}

type Option {
    value: Int
    label: String
}

type Task {
    id: ID!
    goal: String
    dueAt: Date
    context: String
    owner: User
    scope: Option
    effort: Int
    dependsOn: [Task!]!
    numOfUnknowns: Int
    availableActions: [TaskAction!]
    availableScopes: [Option!]!
}

type User {
    id: ID!
    name: String!
    profileUrl: String
}

enum TaskAction {
    START
    DELETE
    ASSIGN_OWNER
    REPORT_BLOCKED
    COMPLETE
}

scalar Date
scalar Void