schema {
	query: Query
	mutation: Mutation
}

type Query {
	"the current logged in user. If not logged in, show default public viewer"
	me: User!
	task(id: ID!): Task!
	"return all tasks for debug purpose"
	tasks(input: TaskFilter): [Task!]!
	teams(ids: [ID!]): [Team!]!
}


interface Entity {
	id: ID!
	createdAt: Time!
}

########
# Team #
########
type Team {
	id: ID!
	name: String!
	iconUrl: String!
	createdAt: Time!
	creator: User!
	"creator is the owner. In the future there will be features to transfer ownership to other users, just like GitHub repo."
	owner: User!
	"creator is the only admin for now"
	admins: [User!]!
	members: [User!]!
	tasks(input: TaskFilter): [Task!]!
	tasksNeedAttention(isMine: Boolean = false): [Task!]!
}

input CreateTeamInput {
	name: String!
}

input UpdateTeamInput {
	id: ID!
}


###########
# Comment #
###########
type Comment {
	id: ID!
	content: String!
	commenter: User!
	task: Task!
	createdAt: Time!
	# mentions: [Mention!]!
}

########
# User #
########
type User implements Entity {
	id: ID!
	lastName: String!
	firstName: String!
	profileUrl: String!
	createdAt: Time!
	activeTeam: Team
	teams(ids: [ID!]): [Team!]!
	"""
	If input is null, return all related tasks.
	Ignore TaskFilter.creatorID
	"""
	tasks(input: TaskFilter): [Task!]!
}

input UserInput {
	id: ID!
	lastName: String
	firstName: String
	profileUrl: String
}

########
# Task #
########
type Task {
	id: ID!
	goal: String!
	context: String!
	creator: User!
	owner: User
	ownedByTeam: Team
	status: TaskStatus!
	comments: [Comment!]!
	# Relationships with other entities
	mentions: [Mention!]!
	# Time Flow
	createdAt: Time!
	dueAt: Time
	availableActions: [TaskAction!]!
	lifetimeEvents: [LifetimeEvent!]!
}

input TaskFilter {
	id: ID
	creatorId: ID
	ownerId: ID
	"a string filter that searches in both goal and context. Not Implemented."
	text: String
	status: TaskStatus
}

enum TaskAction {
	START
	DELETE
	ASSIGN_OWNER
	REPORT_BLOCKED
	MARK_COMPLETE
}

enum TaskStatus {
	UPCOMING
	IN_PROGRESS
	DELIVERED
}

input TaskInput {
	goal: String
	dueAt: Time
	context: String
	ownerUserId: ID
	status: TaskStatus
}


"""
LifetimeEvent
"""
type LifetimeEvent {
    id: ID!
	# todo: will add eventType & actor when v1 is merged with v2
    # eventType: LifetimeEventType!
    "who did it"
    # actor:     User!
	actorID:   ID!
    happensAt: Time!
}

"""
Mention is a backend computed value according to text content of task or comments
so that frontend doesn't need to compute is again.
"""
type Mention {
	# todo: will add when v2 User & Task is merged into v1
	# mentionable: Mentionable!
	"""
	offset is the 0-based index of the starting of the mentioned text.
	The frontend can use this information to heightlight/replace/hyperlink the substring
	"""
	offset: Int!
	"the length of the mentioned text"
	limit: Int!
}

union Mentionable = User | Task

scalar Time

"""
Mutation
"""
type Mutation {
	#########
	# Tasks #
	"A task can exist independently from a team"
	createTask(task: TaskCreationInput!): TaskUpdate!
	updateTask(taskId: ID!, task: TaskInput!): Task!
	deleteTask(taskId: ID!): Task!

	############
	# Comments #
	comment(id: ID!): 						      CommentUpdate!
	createComment(taskId: ID!, content: String!): Comment!

	#########
	# Teams #
	team(id: ID!): TeamUpdate!
	createTeam(input: CreateTeamInput!): TeamUpdate!

	#########
	# Users #
	user(id: ID!): UserUpdate!
	"""
	todo: implement a directive that hide this resolver from production
		  or when the logged in user is not a system admin
	Admin && Debug Only resolvers
	"""
	createUser(input: UserInput!): UserUpdate!

	promoteTaskToNeedAttention(taskId: ID!): Team!	@deprecated(reason: "use TeamUpdate")
	updateActiveTeam(teamId: ID!): User!			@deprecated(reason: "use UserUpdate")
}

input TaskCreationInput {
	goal: String
	context: String
	dueAt: Time
	ownerUserId: ID
	status: TaskStatus
}

type TaskUpdate {
	"change ownedByTeam of task field to id"
	ownedByTeam(id: ID!): TaskUpdate!
	task: Task!
}

input UserUpdateInput {
	lastName: String
	firstName: String
	profileUrl: String
}

type UserUpdate {
	updateActiveTeam(teamId: ID!): UserUpdate!
	updateUser(input: UserUpdateInput!): UserUpdate!
	user: User!
}

input TeamUpdateInput {
	name:       String
	iconUrl: String
}

type TeamUpdate {
	"Given the user id, add the user to the team."
	addMember(id: ID!): TeamUpdate!
	removeMember(id: ID!): TeamUpdate!
	update(input: TeamUpdateInput!): TeamUpdate!
	"Given the task id, promote an In Progress task to Need Attention."
	promoteTaskToNeedAttention(Id: ID!): TeamUpdate!
	"get the value of this team"
	team: Team!
}

type CommentUpdate {
	updateContent(content: String!): CommentUpdate!
	delete: Comment!
	comment: Comment!
}
