schema {
	query: Query
	mutation: Mutation
}

type Query {
	executionMode: ExecutionMode!
	task(id: ID!): Task!
	activeTeam: Team
}

type Mutation {
	createTask(task: TaskInput!): Boolean!
	deleteTask(taskId: ID!): Boolean!
	updateTask(taskId: ID!, task: TaskInput!): Boolean!
	startTask(taskId: ID!): Boolean!
	performTaskAction(taskId: ID!, action: TaskAction!): Boolean!
}

input TaskInput {
	goal: String
	dueAt: Time
	context: String
	ownerUserID: ID
	workScopeIndex: Int
	dependsOnTaskIds: [ID!]
	numOfUnknowns: Int
}

interface Entity {
	id: ID!
	createdAt: Time!
	updatedAt: Time
}

type Team {
	members: [User!]!
}

type ExecutionMode {
	personalStatus: PersonalStatus!
	teamStatus: TeamStatus!
}

type PersonalStatus {
	taskNeedAttention: Task
	upcomingTasks: [Task!]!
	deliveredTasks: [Task!]!
}

type TeamStatus {
	upcomingTasks: [Task!]!
	inProgressTasks: [Task!]!
	deliveredTasks: [Task!]!
}

type Option {
	value: Int!
	label: String!
}

type Task implements Entity {
	id: ID!
	goal: String!
	dueAt: Time
	context: String
	owner: User
	workScope: Option!
	effort: Int
	dependsOn: [Task!]!
	numOfUnknowns: Int
	availableActions: [TaskAction!]!
	availableWorkScopes: [Option!]!
	createdAt: Time!
	updatedAt: Time
	lifetimeEvents: [LifetimeEvent!]!
}

type User implements Entity {
	id: ID!
	name: String!
	profileUrl: String!
	createdAt: Time!
	updatedAt: Time
}

enum TaskAction {
	START
	DELETE
	ASSIGN_OWNER
	REPORT_BLOCKED
	MARK_COMPLETE
}

scalar Time

"""
LifetimeEvent
"""
type LifetimeEvent {
    id: ID!
	# todo: will add eventType & actor when v1 is merged with v2
    # eventType: LifetimeEventType!
    "who did it"
    # actor:     User!
	actorID:   ID!
    happensAt: Time!
}

