// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dep

import (
	"database/sql"
	"github.com/teamyapp/cloud/app/api"
	"github.com/teamyapp/cloud/libs/telemetry"
	"github.com/teamyapp/teamy-backend/apps/dao/sqldb"
	"github.com/teamyapp/teamy-backend/apps/github"
	api2 "github.com/teamyapp/teamy-backend/core/api"
)

// Injectors from wire.go:

func InitDataCollector(serviceName string, visibleLevel telemetry.LogLevel) telemetry.DataCollector {
	logger := newLogger(serviceName, visibleLevel)
	dataCollector := telemetry.NewDataCollector(logger)
	return dataCollector
}

func InitGithubApp(dataCollector telemetry.DataCollector, cloudAPIClientRegistry *api.ClientRegistry, teamyAPIClientRegistry *api2.ClientRegistry, config github.AppConfig, sqlDB *sql.DB) (github.App, error) {
	githubAppInstallState := sqldb.NewGithubAppInstallState(dataCollector, sqlDB)
	githubAppInstallation := sqldb.NewGithubAppInstallation(dataCollector, sqlDB)
	githubPullRequest := sqldb.NewGithubPullRequest(dataCollector, sqlDB)
	githubCodeReview := sqldb.NewGithubCodeReview(dataCollector, sqlDB)
	githubRequiredUserAction := sqldb.NewGithubRequiredUserAction(dataCollector, sqlDB)
	app := github.NewApp(config, dataCollector, cloudAPIClientRegistry, teamyAPIClientRegistry, githubAppInstallState, githubAppInstallation, githubPullRequest, githubCodeReview, githubRequiredUserAction)
	return app, nil
}

// wire.go:

func newLogger(serviceName string, visibleLevel telemetry.LogLevel) telemetry.Logger {
	return telemetry.NewServiceLogger(serviceName, telemetry.NewRequestLogger(telemetry.NewRawLogger(visibleLevel)))
}
