// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"

	"github.com/teamyapp/cloud/app/api"
	"github.com/teamyapp/cloud/app/config"
	"github.com/teamyapp/teamy-backend/apps"
	config2 "github.com/teamyapp/teamy-backend/apps/config"
	"github.com/teamyapp/teamy-backend/apps/dao/sqldb"
)

// Injectors from wire.go:

func InitGithubApp(cloudAPICfg config.CloudAPIClient, config3 config2.GithubAppConfig, sqlDB *sql.DB) (apps.GithubApp, error) {
	cloudAPIClient, err := api.NewCloudAPIClient(cloudAPICfg)
	if err != nil {
		return apps.GithubApp{}, err
	}
	githubAppInstallState := sqldb.NewGithubAppInstallState(sqlDB)
	githubAppInstallation := sqldb.NewGithubAppInstallation(sqlDB)
	githubApp := apps.NewGithubApp(config3, cloudAPIClient, githubAppInstallState, githubAppInstallation)
	return githubApp, nil
}
