// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"
	"github.com/teamyapp/cloud/app/api"
	"github.com/teamyapp/cloud/libs/gql"
	"github.com/teamyapp/cloud/libs/telemetry"
	"github.com/teamyapp/cloud/libs/web"
	"github.com/teamyapp/teamy-backend/apps/dao/sqldb"
	"github.com/teamyapp/teamy-backend/apps/github"
	"github.com/teamyapp/teamy-backend/apps/github/client"
	api2 "github.com/teamyapp/teamy-backend/core/api"
)

// Injectors from wire.go:

func InitGithubAppAPI(logger telemetry.Logger, cloudAPIClientRegistry *api.ClientRegistry, teamyAPIClientRegistry *api2.ClientRegistry, httpClient web.HTTPClient, config github.AppConfig, githubAppPrivateKeyPEM GithubAppPrivateKeyPEM, sqlDB *sql.DB) (github.AppAPI, error) {
	githubAppInstallState := sqldb.NewGithubAppInstallState(logger, sqlDB)
	githubAppInstallation := sqldb.NewGithubAppInstallation(logger, sqlDB)
	githubPullRequest := sqldb.NewGithubPullRequest(logger, sqlDB)
	githubCodeReview := sqldb.NewGithubCodeReview(logger, sqlDB)
	githubRequiredUserAction := sqldb.NewGithubRequiredUserAction(logger, sqlDB)
	githubPullRequestInternalTaskRelation := sqldb.NewGithubPullRequestInternalTaskRelation(logger, sqlDB)
	gqlClient := gql.NewClient(logger, httpClient)
	graphQLAPI := client.NewGraphQLAPI(logger, gqlClient)
	restapi := client.NewRESTAPI(logger, httpClient)
	githubApp, err := newGithubApp(logger, config, githubAppPrivateKeyPEM)
	if err != nil {
		return github.AppAPI{}, err
	}
	appAPI := github.NewAppAPI(config, logger, cloudAPIClientRegistry, teamyAPIClientRegistry, githubAppInstallState, githubAppInstallation, githubPullRequest, githubCodeReview, githubRequiredUserAction, githubPullRequestInternalTaskRelation, graphQLAPI, restapi, githubApp)
	return appAPI, nil
}

// wire.go:

type GithubAppPrivateKeyPEM []byte

func newGithubApp(logger telemetry.Logger, config github.AppConfig, privateKeyPEM GithubAppPrivateKeyPEM) (*client.GithubApp, error) {
	return client.NewGithubApp(logger, config.AppID, []byte(privateKeyPEM))
}
