kind: pipeline
type: kubernetes
name: feature

steps:
  - name: retrieve cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: retrieve
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: run unit tests
    image: golang:1.18
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
    commands:
      - go test ./...
  - name: persist cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: persist
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: code
    when:
      status: [ success, failure ]
volumes:
  - name: go-mod-cache
    temp: {}
  - name: cache
    host:
      path: /var/lib/cache
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
---
kind: pipeline
type: kubernetes
name: testing

steps:
  - name: retrieve cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: retrieve
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: build app
    image: golang:1.18-alpine
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
    commands:
      - sh ./scripts/build.sh
  - name: build & publish Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: registry.digitalocean.com/teamyapp/teamy-backend-testing
      registry: registry.digitalocean.com
  - name: notify image update
    image: plugins/webhook
    settings:
      urls: http://keel.deploy.svc.cluster.local:9300/v1/webhooks/native
      template: |
        {
          "name": "registry.digitalocean.com/teamyapp/teamy-backend-testing",
          "tag": "latest"
        }
  - name: persist cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: persist
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: code
    when:
      status: [ success, failure ]
volumes:
  - name: go-mod-cache
    temp: {}
  - name: cache
    host:
      path: /var/lib/cache
trigger:
  branch:
    - testing
  event:
    - push
---
kind: pipeline
type: kubernetes
name: staging

steps:
  - name: retrieve cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: retrieve
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: build app
    image: golang:1.18-alpine
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
    commands:
      - sh ./scripts/build.sh
  - name: build & publish Docker image
    image: plugins/docker
    environment:
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: registry.digitalocean.com/teamyapp/teamy-backend-staging
      registry: registry.digitalocean.com
  - name: notify image update
    image: plugins/webhook
    settings:
      urls: http://keel.deploy.svc.cluster.local:9300/v1/webhooks/native
      template: |
        {
          "name": "registry.digitalocean.com/teamyapp/teamy-backend-staging",
          "tag": "latest"
        }
  - name: persist cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: persist
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: code
    when:
      status: [ success, failure ]
volumes:
  - name: go-mod-cache
    temp: {}
  - name: cache
    host:
      path: /var/lib/cache
trigger:
  branch:
    - master
    - main
  event:
    - push
---
kind: pipeline
type: kubernetes
name: production

steps:
  - name: retrieve cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: retrieve
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: build app
    image: golang:1.18-alpine
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
    commands:
      - sh ./scripts/build.sh
  - name: build & publish Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: registry.digitalocean.com/teamyapp/teamy-backend
      registry: registry.digitalocean.com
  - name: notify image update
    image: plugins/webhook
    settings:
      urls: http://keel.deploy.svc.cluster.local:9300/v1/webhooks/native
      template: |
        {
          "name": "registry.digitalocean.com/teamyapp/teamy-backend",
          "tag": "latest"
        }
  - name: persist cache
    image: ghcr.io/teamyapp/drone-cache:0.1.9
    volumes:
      - name: go-mod-cache
        path: /go/pkg/mod
      - name: cache
        path: /var/lib/cache
    settings:
      mode: persist
      version_file_path: go.sum
      cacheable_absolute_paths:
        - /go/pkg/mod
      storage_type: volume
      volume_cache_root_dir: /var/lib/cache
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: code
    when:
      status: [ success, failure ]
volumes:
  - name: go-mod-cache
    temp: {}
  - name: cache
    host:
      path: /var/lib/cache
trigger:
  branch:
    - production
  event:
    - push

