// Code generated by Cloud CLI. DO NOT EDIT.
package authorization

import (
	"github.com/teamyapp/cloud/libs/authorization"
)

func NewCreateAppVersionInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "CreateAppVersion",
		UserID:       currUserID,
	}
}
func NewCreateAppVersionVisibleTeamInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "CreateAppVersionVisibleTeam",
		UserID:       currUserID,
	}
}
func NewCreateTeamInstallationInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "CreateTeamInstallation",
		UserID:       currUserID,
	}
}
func NewDeleteInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "Delete",
		UserID:       currUserID,
	}
}
func NewDeleteAppVersionInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "DeleteAppVersion",
		UserID:       currUserID,
	}
}
func NewDeleteAppVersionVisibleTeamInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "DeleteAppVersionVisibleTeam",
		UserID:       currUserID,
	}
}
func NewDeleteTeamInstallationInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "DeleteTeamInstallation",
		UserID:       currUserID,
	}
}
func NewReadInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "Read",
		UserID:       currUserID,
	}
}
func NewRefreshAppSecretInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "RefreshAppSecret",
		UserID:       currUserID,
	}
}
func NewUpdateInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "Update",
		UserID:       currUserID,
	}
}
func NewUpdateAppVersionInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "UpdateAppVersion",
		UserID:       currUserID,
	}
}
func NewUpdateTeamInstallationInAppQuery(currUserID uint64, appID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "UpdateTeamInstallation",
		UserID:       currUserID,
	}
}

func NewDeleteInInvitationQuery(currUserID uint64, invitationID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: InvitationResourceType,
		ResourceID:   invitationID,
		Operation:    "Delete",
		UserID:       currUserID,
	}
}
func NewReadInInvitationQuery(currUserID uint64, invitationID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: InvitationResourceType,
		ResourceID:   invitationID,
		Operation:    "Read",
		UserID:       currUserID,
	}
}
func NewUpdateInInvitationQuery(currUserID uint64, invitationID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: InvitationResourceType,
		ResourceID:   invitationID,
		Operation:    "Update",
		UserID:       currUserID,
	}
}

func NewAddTaskToInSprintQuery(currUserID uint64, sprintID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: SprintResourceType,
		ResourceID:   sprintID,
		Operation:    "AddTaskTo",
		UserID:       currUserID,
	}
}
func NewDeleteInSprintQuery(currUserID uint64, sprintID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: SprintResourceType,
		ResourceID:   sprintID,
		Operation:    "Delete",
		UserID:       currUserID,
	}
}
func NewReadInSprintQuery(currUserID uint64, sprintID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: SprintResourceType,
		ResourceID:   sprintID,
		Operation:    "Read",
		UserID:       currUserID,
	}
}
func NewRemoveTaskFromInSprintQuery(currUserID uint64, sprintID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: SprintResourceType,
		ResourceID:   sprintID,
		Operation:    "RemoveTaskFrom",
		UserID:       currUserID,
	}
}
func NewUpdateInSprintQuery(currUserID uint64, sprintID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: SprintResourceType,
		ResourceID:   sprintID,
		Operation:    "Update",
		UserID:       currUserID,
	}
}

func NewAddAwaitForTaskInTaskQuery(currUserID uint64, taskID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "AddAwaitForTask",
		UserID:       currUserID,
	}
}
func NewCreateLinkInTaskQuery(currUserID uint64, taskID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "CreateLink",
		UserID:       currUserID,
	}
}
func NewDeleteInTaskQuery(currUserID uint64, taskID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "Delete",
		UserID:       currUserID,
	}
}
func NewMoveBetweenContainersInTaskQuery(currUserID uint64, taskID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "MoveBetweenContainers",
		UserID:       currUserID,
	}
}
func NewReadInTaskQuery(currUserID uint64, taskID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "Read",
		UserID:       currUserID,
	}
}
func NewRemoveAwaitForTaskInTaskQuery(currUserID uint64, taskID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "RemoveAwaitForTask",
		UserID:       currUserID,
	}
}
func NewUpdateInTaskQuery(currUserID uint64, taskID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "Update",
		UserID:       currUserID,
	}
}

func NewDeleteInTaskLinkQuery(currUserID uint64, taskLinkID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskLinkResourceType,
		ResourceID:   taskLinkID,
		Operation:    "Delete",
		UserID:       currUserID,
	}
}
func NewReadInTaskLinkQuery(currUserID uint64, taskLinkID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskLinkResourceType,
		ResourceID:   taskLinkID,
		Operation:    "Read",
		UserID:       currUserID,
	}
}
func NewUpdateInTaskLinkQuery(currUserID uint64, taskLinkID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TaskLinkResourceType,
		ResourceID:   taskLinkID,
		Operation:    "Update",
		UserID:       currUserID,
	}
}

func NewAddAwaitForTaskInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "AddAwaitForTask",
		UserID:       currUserID,
	}
}
func NewAddMemberToInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "AddMemberTo",
		UserID:       currUserID,
	}
}
func NewCloneTaskInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CloneTask",
		UserID:       currUserID,
	}
}
func NewCreateAppInstallationInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateAppInstallation",
		UserID:       currUserID,
	}
}
func NewCreateInvitationInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateInvitation",
		UserID:       currUserID,
	}
}
func NewCreateSprintInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateSprint",
		UserID:       currUserID,
	}
}
func NewCreateTaskInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateTask",
		UserID:       currUserID,
	}
}
func NewCreateTaskLinkInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateTaskLink",
		UserID:       currUserID,
	}
}
func NewDeleteInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "Delete",
		UserID:       currUserID,
	}
}
func NewDeleteAppInstallationInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DeleteAppInstallation",
		UserID:       currUserID,
	}
}
func NewDeleteInvitationInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DeleteInvitation",
		UserID:       currUserID,
	}
}
func NewDeleteSprintInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DeleteSprint",
		UserID:       currUserID,
	}
}
func NewDeleteTaskInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DeleteTask",
		UserID:       currUserID,
	}
}
func NewDemoteMemberFromAdminInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DemoteMemberFromAdmin",
		UserID:       currUserID,
	}
}
func NewMoveTaskBetweenContainersInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "MoveTaskBetweenContainers",
		UserID:       currUserID,
	}
}
func NewPromoteMemberToAdminInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "PromoteMemberToAdmin",
		UserID:       currUserID,
	}
}
func NewReadInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "Read",
		UserID:       currUserID,
	}
}
func NewReadInvitationInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "ReadInvitation",
		UserID:       currUserID,
	}
}
func NewReadMembersInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "ReadMembers",
		UserID:       currUserID,
	}
}
func NewReadSprintInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "ReadSprint",
		UserID:       currUserID,
	}
}
func NewReadTaskInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "ReadTask",
		UserID:       currUserID,
	}
}
func NewRemoveAwaitForTaskInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "RemoveAwaitForTask",
		UserID:       currUserID,
	}
}
func NewRemoveMemberFromInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "RemoveMemberFrom",
		UserID:       currUserID,
	}
}
func NewUpdateInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "Update",
		UserID:       currUserID,
	}
}
func NewUpdateAppInstallationInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateAppInstallation",
		UserID:       currUserID,
	}
}
func NewUpdateInvitationInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateInvitation",
		UserID:       currUserID,
	}
}
func NewUpdateMembersInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateMembers",
		UserID:       currUserID,
	}
}
func NewUpdateSprintInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateSprint",
		UserID:       currUserID,
	}
}
func NewUpdateTaskInTeamQuery(currUserID uint64, teamID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateTask",
		UserID:       currUserID,
	}
}

func NewDeleteInUserQuery(currUserID uint64, userID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: UserResourceType,
		ResourceID:   userID,
		Operation:    "Delete",
		UserID:       currUserID,
	}
}
func NewReadInUserQuery(currUserID uint64, userID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: UserResourceType,
		ResourceID:   userID,
		Operation:    "Read",
		UserID:       currUserID,
	}
}
func NewUpdateInUserQuery(currUserID uint64, userID uint64) authorization.Query {
	return authorization.Query{
		ResourceType: UserResourceType,
		ResourceID:   userID,
		Operation:    "Update",
		UserID:       currUserID,
	}
}
