// Code generated by Cloud CLI. DO NOT EDIT.
package authorization

import "fmt"

type Query struct {
	ResourceType ResourceType
	ResourceID   uint64
	Operation    string
	UserID       uint64
}

func NewReadInTaskQuery(userID uint64, taskID uint64) Query {
	return Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "Read",
		UserID:       userID,
	}
}
func NewUpdateInTaskQuery(userID uint64, taskID uint64) Query {
	return Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "Update",
		UserID:       userID,
	}
}
func NewDeleteInTaskQuery(userID uint64, taskID uint64) Query {
	return Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "Delete",
		UserID:       userID,
	}
}
func NewCreateLinkInTaskQuery(userID uint64, taskID uint64) Query {
	return Query{
		ResourceType: TaskResourceType,
		ResourceID:   taskID,
		Operation:    "CreateLink",
		UserID:       userID,
	}
}

func NewReadInTaskLinkQuery(userID uint64, taskLinkID uint64) Query {
	return Query{
		ResourceType: TaskLinkResourceType,
		ResourceID:   taskLinkID,
		Operation:    "Read",
		UserID:       userID,
	}
}
func NewUpdateInTaskLinkQuery(userID uint64, taskLinkID uint64) Query {
	return Query{
		ResourceType: TaskLinkResourceType,
		ResourceID:   taskLinkID,
		Operation:    "Update",
		UserID:       userID,
	}
}
func NewDeleteInTaskLinkQuery(userID uint64, taskLinkID uint64) Query {
	return Query{
		ResourceType: TaskLinkResourceType,
		ResourceID:   taskLinkID,
		Operation:    "Delete",
		UserID:       userID,
	}
}

func NewReadInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "Read",
		UserID:       userID,
	}
}
func NewUpdateInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "Update",
		UserID:       userID,
	}
}
func NewDeleteInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "Delete",
		UserID:       userID,
	}
}
func NewReadTaskInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "ReadTask",
		UserID:       userID,
	}
}
func NewCreateTaskInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateTask",
		UserID:       userID,
	}
}
func NewUpdateTaskInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateTask",
		UserID:       userID,
	}
}
func NewDeleteTaskInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DeleteTask",
		UserID:       userID,
	}
}
func NewCloneTaskInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CloneTask",
		UserID:       userID,
	}
}
func NewCreateTaskLinkInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateTaskLink",
		UserID:       userID,
	}
}
func NewReadMembersInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "ReadMembers",
		UserID:       userID,
	}
}
func NewAddMemberToInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "AddMemberTo",
		UserID:       userID,
	}
}
func NewRemoveMemberFromInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "RemoveMemberFrom",
		UserID:       userID,
	}
}
func NewUpdateMembersInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateMembers",
		UserID:       userID,
	}
}
func NewReadSprintInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "ReadSprint",
		UserID:       userID,
	}
}
func NewCreateSprintInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateSprint",
		UserID:       userID,
	}
}
func NewUpdateSprintInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateSprint",
		UserID:       userID,
	}
}
func NewDeleteSprintInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DeleteSprint",
		UserID:       userID,
	}
}
func NewReadInvitationInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "ReadInvitation",
		UserID:       userID,
	}
}
func NewCreateInvitationInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateInvitation",
		UserID:       userID,
	}
}
func NewUpdateInvitationInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateInvitation",
		UserID:       userID,
	}
}
func NewDeleteInvitationInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DeleteInvitation",
		UserID:       userID,
	}
}
func NewCreateAppInstallationInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "CreateAppInstallation",
		UserID:       userID,
	}
}
func NewUpdateAppInstallationInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "UpdateAppInstallation",
		UserID:       userID,
	}
}
func NewDeleteAppInstallationInTeamQuery(userID uint64, teamID uint64) Query {
	return Query{
		ResourceType: TeamResourceType,
		ResourceID:   teamID,
		Operation:    "DeleteAppInstallation",
		UserID:       userID,
	}
}

func NewReadInSprintQuery(userID uint64, sprintID uint64) Query {
	return Query{
		ResourceType: SprintResourceType,
		ResourceID:   sprintID,
		Operation:    "Read",
		UserID:       userID,
	}
}
func NewUpdateInSprintQuery(userID uint64, sprintID uint64) Query {
	return Query{
		ResourceType: SprintResourceType,
		ResourceID:   sprintID,
		Operation:    "Update",
		UserID:       userID,
	}
}
func NewDeleteInSprintQuery(userID uint64, sprintID uint64) Query {
	return Query{
		ResourceType: SprintResourceType,
		ResourceID:   sprintID,
		Operation:    "Delete",
		UserID:       userID,
	}
}

func NewReadInInvitationQuery(userID uint64, invitationID uint64) Query {
	return Query{
		ResourceType: InvitationResourceType,
		ResourceID:   invitationID,
		Operation:    "Read",
		UserID:       userID,
	}
}
func NewCreateInInvitationQuery(userID uint64, invitationID uint64) Query {
	return Query{
		ResourceType: InvitationResourceType,
		ResourceID:   invitationID,
		Operation:    "Create",
		UserID:       userID,
	}
}
func NewDeleteInInvitationQuery(userID uint64, invitationID uint64) Query {
	return Query{
		ResourceType: InvitationResourceType,
		ResourceID:   invitationID,
		Operation:    "Delete",
		UserID:       userID,
	}
}

func NewReadInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "Read",
		UserID:       userID,
	}
}
func NewUpdateInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "Update",
		UserID:       userID,
	}
}
func NewDeleteInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "Delete",
		UserID:       userID,
	}
}
func NewRefreshAppSecretInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "RefreshAppSecret",
		UserID:       userID,
	}
}
func NewCreateAppVersionInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "CreateAppVersion",
		UserID:       userID,
	}
}
func NewUpdateAppVersionInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "UpdateAppVersion",
		UserID:       userID,
	}
}
func NewDeleteAppVersionInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "DeleteAppVersion",
		UserID:       userID,
	}
}
func NewCreateAppVersionVisibleTeamInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "CreateAppVersionVisibleTeam",
		UserID:       userID,
	}
}
func NewDeleteAppVersionVisibleTeamInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "DeleteAppVersionVisibleTeam",
		UserID:       userID,
	}
}
func NewCreateTeamInstallationInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "CreateTeamInstallation",
		UserID:       userID,
	}
}
func NewUpdateTeamInstallationInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "UpdateTeamInstallation",
		UserID:       userID,
	}
}
func NewDeleteTeamInstallationInAppQuery(userID uint64, appID uint64) Query {
	return Query{
		ResourceType: AppResourceType,
		ResourceID:   appID,
		Operation:    "DeleteTeamInstallation",
		UserID:       userID,
	}
}

func (q Query) String() string {
	return fmt.Sprintf("[Query UserID=%v Operation=%v ResourceType=%v ResourceID=%v]", q.UserID, q.Operation, q.ResourceType, q.ResourceID)
}
