// Code generated by Cloud CLI. DO NOT EDIT.
package authorization

import (
	"github.com/teamyapp/cloud/libs/authorization"
)

// Operations for Task
var (
	ReadInTask = authorization.ResourceTypeOperation{
		ResourceType: "Task",
		Operation:    "Read",
	}
	UpdateInTask = authorization.ResourceTypeOperation{
		ResourceType: "Task",
		Operation:    "Update",
	}
	DeleteInTask = authorization.ResourceTypeOperation{
		ResourceType: "Task",
		Operation:    "Delete",
	}
	CreateLinkInTask = authorization.ResourceTypeOperation{
		ResourceType: "Task",
		Operation:    "CreateLink",
	}
)

// Operations for TaskLink
var (
	ReadInTaskLink = authorization.ResourceTypeOperation{
		ResourceType: "TaskLink",
		Operation:    "Read",
	}
	UpdateInTaskLink = authorization.ResourceTypeOperation{
		ResourceType: "TaskLink",
		Operation:    "Update",
	}
	DeleteInTaskLink = authorization.ResourceTypeOperation{
		ResourceType: "TaskLink",
		Operation:    "Delete",
	}
)

// Operations for Team
var (
	ReadInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "Read",
	}
	UpdateInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "Update",
	}
	DeleteInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "Delete",
	}
	ReadTaskInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "ReadTask",
	}
	CreateTaskInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateTask",
	}
	UpdateTaskInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateTask",
	}
	DeleteTaskInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DeleteTask",
	}
	CloneTaskInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CloneTask",
	}
	CreateTaskLinkInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateTaskLink",
	}
	PromoteMemberToAdminInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "PromoteMemberToAdmin",
	}
	DemoteMemberFromAdminInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DemoteMemberFromAdmin",
	}
	ReadMembersInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "ReadMembers",
	}
	AddMemberToInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "AddMemberTo",
	}
	RemoveMemberFromInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "RemoveMemberFrom",
	}
	UpdateMembersInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateMembers",
	}
	ReadSprintInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "ReadSprint",
	}
	CreateSprintInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateSprint",
	}
	UpdateSprintInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateSprint",
	}
	DeleteSprintInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DeleteSprint",
	}
	ReadInvitationInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "ReadInvitation",
	}
	CreateInvitationInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateInvitation",
	}
	UpdateInvitationInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateInvitation",
	}
	DeleteInvitationInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DeleteInvitation",
	}
	CreateAppInstallationInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateAppInstallation",
	}
	UpdateAppInstallationInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateAppInstallation",
	}
	DeleteAppInstallationInTeam = authorization.ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DeleteAppInstallation",
	}
)

// Operations for Sprint
var (
	ReadInSprint = authorization.ResourceTypeOperation{
		ResourceType: "Sprint",
		Operation:    "Read",
	}
	UpdateInSprint = authorization.ResourceTypeOperation{
		ResourceType: "Sprint",
		Operation:    "Update",
	}
	DeleteInSprint = authorization.ResourceTypeOperation{
		ResourceType: "Sprint",
		Operation:    "Delete",
	}
)

// Operations for Invitation
var (
	ReadInInvitation = authorization.ResourceTypeOperation{
		ResourceType: "Invitation",
		Operation:    "Read",
	}
	CreateInInvitation = authorization.ResourceTypeOperation{
		ResourceType: "Invitation",
		Operation:    "Create",
	}
	DeleteInInvitation = authorization.ResourceTypeOperation{
		ResourceType: "Invitation",
		Operation:    "Delete",
	}
)

// Operations for App
var (
	ReadInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "Read",
	}
	UpdateInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "Update",
	}
	DeleteInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "Delete",
	}
	RefreshAppSecretInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "RefreshAppSecret",
	}
	CreateAppVersionInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "CreateAppVersion",
	}
	UpdateAppVersionInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "UpdateAppVersion",
	}
	DeleteAppVersionInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "DeleteAppVersion",
	}
	CreateAppVersionVisibleTeamInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "CreateAppVersionVisibleTeam",
	}
	DeleteAppVersionVisibleTeamInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "DeleteAppVersionVisibleTeam",
	}
	CreateTeamInstallationInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "CreateTeamInstallation",
	}
	UpdateTeamInstallationInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "UpdateTeamInstallation",
	}
	DeleteTeamInstallationInApp = authorization.ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "DeleteTeamInstallation",
	}
)
