// Code generated by Cloud CLI. DO NOT EDIT.
package authorization

const (
	TaskResourceType       string = "Task"
	TaskLinkResourceType   string = "TaskLink"
	TeamResourceType       string = "Team"
	SprintResourceType     string = "Sprint"
	InvitationResourceType string = "Invitation"
	AppResourceType        string = "App"
)
