// Code generated by Cloud CLI. DO NOT EDIT.
package authorization

type ResourceTypeOperation struct {
	ResourceType ResourceType
	Operation    string
}

// Operations for Task
var (
	ReadInTask = ResourceTypeOperation{
		ResourceType: "Task",
		Operation:    "Read",
	}
	UpdateInTask = ResourceTypeOperation{
		ResourceType: "Task",
		Operation:    "Update",
	}
	DeleteInTask = ResourceTypeOperation{
		ResourceType: "Task",
		Operation:    "Delete",
	}
	CreateLinkInTask = ResourceTypeOperation{
		ResourceType: "Task",
		Operation:    "CreateLink",
	}
)

// Operations for TaskLink
var (
	ReadInTaskLink = ResourceTypeOperation{
		ResourceType: "TaskLink",
		Operation:    "Read",
	}
	UpdateInTaskLink = ResourceTypeOperation{
		ResourceType: "TaskLink",
		Operation:    "Update",
	}
	DeleteInTaskLink = ResourceTypeOperation{
		ResourceType: "TaskLink",
		Operation:    "Delete",
	}
)

// Operations for Team
var (
	ReadInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "Read",
	}
	UpdateInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "Update",
	}
	DeleteInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "Delete",
	}
	ReadTaskInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "ReadTask",
	}
	CreateTaskInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateTask",
	}
	UpdateTaskInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateTask",
	}
	DeleteTaskInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DeleteTask",
	}
	CloneTaskInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CloneTask",
	}
	CreateTaskLinkInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateTaskLink",
	}
	ReadMembersInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "ReadMembers",
	}
	AddMemberToInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "AddMemberTo",
	}
	RemoveMemberFromInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "RemoveMemberFrom",
	}
	UpdateMembersInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateMembers",
	}
	ReadSprintInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "ReadSprint",
	}
	CreateSprintInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateSprint",
	}
	UpdateSprintInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateSprint",
	}
	DeleteSprintInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DeleteSprint",
	}
	ReadInvitationInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "ReadInvitation",
	}
	CreateInvitationInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateInvitation",
	}
	UpdateInvitationInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateInvitation",
	}
	DeleteInvitationInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DeleteInvitation",
	}
	CreateAppInstallationInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "CreateAppInstallation",
	}
	UpdateAppInstallationInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "UpdateAppInstallation",
	}
	DeleteAppInstallationInTeam = ResourceTypeOperation{
		ResourceType: "Team",
		Operation:    "DeleteAppInstallation",
	}
)

// Operations for Sprint
var (
	ReadInSprint = ResourceTypeOperation{
		ResourceType: "Sprint",
		Operation:    "Read",
	}
	UpdateInSprint = ResourceTypeOperation{
		ResourceType: "Sprint",
		Operation:    "Update",
	}
	DeleteInSprint = ResourceTypeOperation{
		ResourceType: "Sprint",
		Operation:    "Delete",
	}
)

// Operations for Invitation
var (
	ReadInInvitation = ResourceTypeOperation{
		ResourceType: "Invitation",
		Operation:    "Read",
	}
	CreateInInvitation = ResourceTypeOperation{
		ResourceType: "Invitation",
		Operation:    "Create",
	}
	DeleteInInvitation = ResourceTypeOperation{
		ResourceType: "Invitation",
		Operation:    "Delete",
	}
)

// Operations for App
var (
	ReadInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "Read",
	}
	UpdateInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "Update",
	}
	DeleteInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "Delete",
	}
	RefreshAppSecretInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "RefreshAppSecret",
	}
	CreateAppVersionInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "CreateAppVersion",
	}
	UpdateAppVersionInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "UpdateAppVersion",
	}
	DeleteAppVersionInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "DeleteAppVersion",
	}
	CreateAppVersionVisibleTeamInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "CreateAppVersionVisibleTeam",
	}
	DeleteAppVersionVisibleTeamInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "DeleteAppVersionVisibleTeam",
	}
	CreateTeamInstallationInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "CreateTeamInstallation",
	}
	UpdateTeamInstallationInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "UpdateTeamInstallation",
	}
	DeleteTeamInstallationInApp = ResourceTypeOperation{
		ResourceType: "App",
		Operation:    "DeleteTeamInstallation",
	}
)
