// Code generated by Cloud CLI. DO NOT EDIT.
package authorization

const (
	AppResourceType        string = "App"
	InvitationResourceType string = "Invitation"
	SprintResourceType     string = "Sprint"
	TaskResourceType       string = "Task"
	TaskLinkResourceType   string = "TaskLink"
	TeamResourceType       string = "Team"
	UserResourceType       string = "User"
)
