schema {
	query: Query
	mutation: Mutation
}

type Query {
	me: User!
	tasks(filter: TaskFilter): [Task!]!
	teams(filter: TeamFilter): [Team!]!
	invitations(filter: InvitationFilter): [Invitation!]!
}

type Mutation {
	# Task
	createTask(teamId: ID!, task: CreateTaskInput!): Task!
	updateTask(taskId: ID!, input: UpdateTaskInput!): Task!
	deleteTask(taskId: ID!): Task!

	# Message
	createMessage(threadId: ID!, message: CreateMessageInput!): Message!
	updateMessage(messageId: ID!, input: UpdateMessageInput!): Message!
	deleteMessage(messageId: ID!): Message!

	# Team
	createTeam(team: CreateTeamInput!): Team!
	updateTeam(teamId: ID!, input: UpdateTeamInput!): Team!
	addMemberToTeam(teamId: ID!, memberId: ID!): Team!
	removeMemberFromTeam(teamId: ID!, memberId: ID!): Team!
	removeTaskFromTeam(teamId: ID!, taskID: ID!): Team!
	promoteTeamTaskToNeedAttention(teamId: ID!, taskId: ID!): Team!

	# User
	createUser(user: CreateUserInput!): User!
	updateUser(userId: ID!, input: UpdateUserInput!): User!

	# Invitation
	createInvitation(teamId: ID!, invitation: CreateInvitationInput!): Invitation!
	updateInvitation(invitationId: ID!, input: UpdateInvitationInput!): Invitation!
	acceptInvitation(invitationCode: String!): Invitation!
	declineInvitation(invitationCode: String!): Invitation!
	deleteInvitation(invitationId: ID!): Invitation!
}

type Task {
	id: ID!
	goal: String!
	context: String
	creator: User!
	owner: User
	owningTeam: Team!
	status: TaskStatus!
	comments: Thread!
	createdAt: Time!
	updatedAt: Time
	dueAt: Time
	availableActions: [TaskAction!]!
}

type Message {
	id: ID!
	body: String!
	author: User!
	thread: Thread!
	createdAt: Time!
	updatedAt: Time
}

type Thread {
	id: ID!
	messages: [Message!]!
}

type Team {
	id: ID!
	name: String!
	iconUrl: String
	createdAt: Time!
	creator: User!
	owner: User!
	members: [User!]!
	tasks(filter: TaskFilter): [Task!]!
	invitations(filter: InvitationFilter): [Invitation!]!
}

type Invitation {
	id: ID!
	sender: User!
	receiverFirstName: String
	receiverLastName: String
	receiverEmail: String
	receiver: User
	joiningTeam: Team!
	expireAt: Time!
	createdAt: Time!
	status: InvitationStatus!
	code: String!
}

enum InvitationStatus {
	PENDING
	ACCEPTED
	DECLINED
	EXPIRED
}

enum TaskAction {
	START
	DELETE
	ASSIGN_OWNER
	REPORT_BLOCKED
	MARK_COMPLETE
}

enum TaskStatus {
	NEED_ATTENTION
	UPCOMING
	IN_PROGRESS
	DELIVERED
}

type User {
	id: ID!
	firstName: String!
	lastName: String!
	profileUrl: String
	createdAt: Time!
	teams(filter: TeamFilter): [Team!]!
}

# Input
input TaskFilter {
	taskId: ID
	ownerId: ID
	goalContains: String
	status: TaskStatus
}

input TeamFilter {
	teamId: ID
}

input InvitationFilter {
	invitationId: ID
	code: String
}

input CreateTaskInput {
	goal: String!
	context: String
	ownerUserId: ID
	dueAt: Time
}

input UpdateTaskInput {
	goal: String!
	context: String
	ownerUserId: ID
	owningTeamId: ID!
	status: TaskStatus!
	effort: Int
	dueAt: Time
}

input CreateMessageInput {
	body: String!
}

input UpdateMessageInput {
	body: String
}

input CreateTeamInput {
	name: String!
}

input UpdateTeamInput {
	name: String
	iconUrl: String
}

input CreateUserInput {
	lastName: String!
	firstName: String!
	profileUrl: String
}

input UpdateUserInput {
	lastName: String
	firstName: String
	profileUrl: String
}

input CreateInvitationInput {
	receiverFirstName: String
	receiverEmail: String
	expireAt: Time!
}

input UpdateInvitationInput {
	senderUserId: ID
	receiverUserId: ID
	expireAt: Time
	status: InvitationStatus
}

scalar Time
