schema {
	query: Query
	mutation: Mutation
}

type Query {
	tasks(input: [TaskFilter!]!): [Task!]!
    users(input: [UserFilter!]!): [User!]!
    me: User!
}

type LifetimeEvent {
    eventType: LifetimeEventEventType!
    "who did it"
    actor:     User!
    happensAt: Time!
}

enum LifetimeEventEventType {
    creation
    change
    close
    archive
    delete
}

enum TaskAction {
	START
	DELETE
	ASSIGN_OWNER
	REPORT_BLOCKED
	MARK_COMPLETE
}

scalar Time
