-- +migrate Up
CREATE TABLE sprint
(
	id BIGINT NOT NULL PRIMARY KEY,
	start_at TIMESTAMP NOT NULL,
	end_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	owning_team_id BIGINT NOT NULL REFERENCES team (id) ON UPDATE CASCADE
);

CREATE TABLE sprint_task_relation
(
	sprint_id BIGINT NOT NULL REFERENCES sprint (id) ON UPDATE CASCADE ON DELETE CASCADE,
	task_id BIGINT NOT NULL REFERENCES task (id) ON UPDATE CASCADE ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE task ADD is_planned BOOLEAN NOT NULL DEFAULT FALSE;

-- +migrate Down
ALTER TABLE task DROP COLUMN is_planned;
DROP TABLE sprint_task_relation;
DROP TABLE sprint;
