-- +migrate Up
ALTER TABLE app_version ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "group" ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE rollout ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE activator ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE version_selector ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;

-- +migrate Down
ALTER TABLE version_selector DROP COLUMN locked;
ALTER TABLE activator DROP COLUMN locked;
ALTER TABLE rollout DROP COLUMN locked;
ALTER TABLE "group" DROP COLUMN locked;
ALTER TABLE app_version DROP COLUMN locked;
