[[target]]
name = "resolver"
type = "goLibrary"
src = [
    "*.go",
]
dep = [
	"(github.com/graph-gophers/graphql-go)",
	"(github.com/teamyapp/one)/entity",
	"(github.com/teamyapp/one)/identity",
	"../../../service",
]
