// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/teamyapp/cloud/app/api"
	"github.com/teamyapp/cloud/libs/obs"
	api2 "github.com/teamyapp/teamy-backend/core/api"
	"github.com/teamyapp/teamy-backend/core/api/gql"
	"github.com/teamyapp/teamy-backend/core/cache"
	"github.com/teamyapp/teamy-backend/core/dao"
	"github.com/teamyapp/teamy-backend/core/dao/sqldb"
	"github.com/teamyapp/teamy-backend/core/realtime"
	"github.com/teamyapp/teamy-backend/core/service"
)

// Injectors from wire.go:

func InitDataCollector(serviceName string, visibleLevel obs.LogLevel) obs.DataCollector {
	logger := newLogger(serviceName, visibleLevel)
	dataCollector := obs.NewDataCollector(logger)
	return dataCollector
}

func InitRealTimeStateSyncer(dataCollector obs.DataCollector, qlDB *sql.DB) *realtime.StateSyncer {
	teamMember := sqldb.NewTeamMember(dataCollector, qlDB)
	stateSyncer := realtime.NewStateSyncer(dataCollector, teamMember)
	return stateSyncer
}

func InitGraphQLAPI(dataCollector obs.DataCollector, cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL, cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) (api2.GraphQL, error) {
	user := sqldb.NewUser(dataCollector, sqlDB)
	team := sqldb.NewTeam(dataCollector, sqlDB)
	task := sqldb.NewTask(dataCollector, sqlDB)
	teamMember := sqldb.NewTeamMember(dataCollector, sqlDB)
	invitation := sqldb.NewInvitation(dataCollector, sqlDB)
	message := sqldb.NewMessage(dataCollector, sqlDB)
	activity := cache.NewActivity(dataCollector)
	taskAwaitForRelation := sqldb.NewTaskAwaitForRelation(dataCollector, sqlDB)
	authorizer := service.NewAuthorizer(dataCollector, cloudAPIClientRegistry)
	thread := sqldb.NewThread(dataCollector, sqlDB)
	sprintParticipant := sqldb.NewSprintParticipant(dataCollector, sqlDB)
	sprintTaskRelation := sqldb.NewSprintTaskRelation(dataCollector, sqlDB)
	serviceThread := service.NewThread(dataCollector, cloudAPIClientRegistry, thread)
	serviceTask := service.NewTask(dataCollector, cloudAPIClientRegistry, authorizer, activity, task, thread, taskAwaitForRelation, sprintParticipant, sprintTaskRelation, serviceThread, realTimeStateSyncer)
	sprint := sqldb.NewSprint(dataCollector, sqlDB)
	teamFileUploadSession := sqldb.NewTeamFileUploadSession(dataCollector, sqlDB)
	serviceSprint := service.NewSprint(dataCollector, cloudAPIClientRegistry, realTimeStateSyncer, authorizer, task, sprint, sprintTaskRelation, sprintParticipant, teamMember, serviceTask)
	serviceTeam := newTeamService(dataCollector, cloudWebAPIExternalBaseURL, cloudAPIClientRegistry, authorizer, realTimeStateSyncer, task, sprint, team, teamMember, teamFileUploadSession, serviceSprint)
	userFileUploadSession := sqldb.NewUserFileUploadSession(dataCollector, sqlDB)
	serviceUser := newUserService(dataCollector, cloudWebAPIExternalBaseURL, cloudAPIClientRegistry, user, userFileUploadSession)
	serviceInvitation := service.NewInvitation(dataCollector, cloudAPIClientRegistry, authorizer, realTimeStateSyncer, invitation)
	dependencies := gql.NewDependencies(dataCollector, cloudAPIClientRegistry, user, team, task, teamMember, invitation, message, activity, taskAwaitForRelation, serviceTask, serviceTeam, serviceSprint, serviceUser, serviceInvitation, realTimeStateSyncer)
	resolver := gql.NewResolver(dependencies)
	graphQL := api2.NewGraphQL(dataCollector, resolver)
	return graphQL, nil
}

func InitRealTimeStateSyncAPI(dataCollector obs.DataCollector, realTimeStateSyncer *realtime.StateSyncer) api2.RealTimeStateSync {
	realTimeStateSync := api2.NewRealTimeStateSync(dataCollector, realTimeStateSyncer)
	return realTimeStateSync
}

func InitTaskRPCAPI(dataCollector obs.DataCollector, cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) api2.TaskRPC {
	authorizer := service.NewAuthorizer(dataCollector, cloudAPIClientRegistry)
	activity := cache.NewActivity(dataCollector)
	task := sqldb.NewTask(dataCollector, sqlDB)
	thread := sqldb.NewThread(dataCollector, sqlDB)
	taskAwaitForRelation := sqldb.NewTaskAwaitForRelation(dataCollector, sqlDB)
	sprintParticipant := sqldb.NewSprintParticipant(dataCollector, sqlDB)
	sprintTaskRelation := sqldb.NewSprintTaskRelation(dataCollector, sqlDB)
	serviceThread := service.NewThread(dataCollector, cloudAPIClientRegistry, thread)
	serviceTask := service.NewTask(dataCollector, cloudAPIClientRegistry, authorizer, activity, task, thread, taskAwaitForRelation, sprintParticipant, sprintTaskRelation, serviceThread, realTimeStateSyncer)
	taskRPC := api2.NewTaskRPC(dataCollector, serviceTask)
	return taskRPC
}

func InitSprintRPCAPI(dataCollector obs.DataCollector, cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) api2.SprintRPC {
	authorizer := service.NewAuthorizer(dataCollector, cloudAPIClientRegistry)
	task := sqldb.NewTask(dataCollector, sqlDB)
	sprint := sqldb.NewSprint(dataCollector, sqlDB)
	sprintTaskRelation := sqldb.NewSprintTaskRelation(dataCollector, sqlDB)
	sprintParticipant := sqldb.NewSprintParticipant(dataCollector, sqlDB)
	teamMember := sqldb.NewTeamMember(dataCollector, sqlDB)
	activity := cache.NewActivity(dataCollector)
	thread := sqldb.NewThread(dataCollector, sqlDB)
	taskAwaitForRelation := sqldb.NewTaskAwaitForRelation(dataCollector, sqlDB)
	serviceThread := service.NewThread(dataCollector, cloudAPIClientRegistry, thread)
	serviceTask := service.NewTask(dataCollector, cloudAPIClientRegistry, authorizer, activity, task, thread, taskAwaitForRelation, sprintParticipant, sprintTaskRelation, serviceThread, realTimeStateSyncer)
	serviceSprint := service.NewSprint(dataCollector, cloudAPIClientRegistry, realTimeStateSyncer, authorizer, task, sprint, sprintTaskRelation, sprintParticipant, teamMember, serviceTask)
	sprintRPC := api2.NewSprintRPC(dataCollector, serviceSprint)
	return sprintRPC
}

// wire.go:

type CloudWebAPIExternalBaseURL string

var daoSet = wire.NewSet(wire.Bind(new(dao.Invitation), new(sqldb.Invitation)), wire.Bind(new(dao.Message), new(sqldb.Message)), wire.Bind(new(dao.Task), new(sqldb.Task)), wire.Bind(new(dao.Team), new(sqldb.Team)), wire.Bind(new(dao.TeamMember), new(sqldb.TeamMember)), wire.Bind(new(dao.User), new(sqldb.User)), wire.Bind(new(dao.Thread), new(sqldb.Thread)), wire.Bind(new(dao.Sprint), new(sqldb.Sprint)), wire.Bind(new(dao.TaskAwaitForRelation), new(sqldb.TaskAwaitForRelation)), wire.Bind(new(dao.SprintTaskRelation), new(sqldb.SprintTaskRelation)), wire.Bind(new(dao.UserFileUploadSession), new(sqldb.UserFileUploadSession)), wire.Bind(new(dao.TeamFileUploadSession), new(sqldb.TeamFileUploadSession)), wire.Bind(new(dao.SprintParticipant), new(sqldb.SprintParticipant)), sqldb.NewInvitation, sqldb.NewMessage, sqldb.NewTask, sqldb.NewTeam, sqldb.NewTeamMember, sqldb.NewUser, sqldb.NewThread, sqldb.NewSprint, sqldb.NewTaskAwaitForRelation, sqldb.NewSprintTaskRelation, sqldb.NewUserFileUploadSession, sqldb.NewTeamFileUploadSession, sqldb.NewSprintParticipant)

var serviceSet = wire.NewSet(service.NewThread, service.NewTask, service.NewInvitation, newTeamService, service.NewSprint, newUserService, service.NewAuthorizer)

func newUserService(
	dataCollector obs.DataCollector,
	cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL,
	cloudClientRegistry *api.ClientRegistry,
	userDao dao.User,
	userFileUploadSessionDao dao.UserFileUploadSession,
) service.User {
	return service.NewUser(
		dataCollector,
		string(cloudWebAPIExternalBaseURL),
		cloudClientRegistry,
		userDao,
		userFileUploadSessionDao)
}

func newTeamService(
	dataCollector obs.DataCollector,
	cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL,
	cloudClientRegistry *api.ClientRegistry,
	authorizer service.Authorizer,
	stateSyncer *realtime.StateSyncer,
	taskDao dao.Task,
	sprintDao dao.Sprint,
	teamDao dao.Team,
	teamMemberDao dao.TeamMember,
	teamFileUploadSessionDao dao.TeamFileUploadSession,
	sprintService service.Sprint,
) service.Team {
	return service.NewTeam(
		dataCollector,
		string(cloudWebAPIExternalBaseURL),
		cloudClientRegistry,
		authorizer,
		stateSyncer,
		taskDao,
		sprintDao,
		teamDao,
		teamMemberDao,
		teamFileUploadSessionDao,
		sprintService)
}

func newLogger(serviceName string, visibleLevel obs.LogLevel) obs.Logger {
	return obs.NewServiceLogger(serviceName, obs.NewRequestLogger(obs.NewClientLogger(realtime.NewMutationLogger(obs.NewRawLogger(visibleLevel)))))
}
