// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/teamyapp/cloud/app/api"
	"github.com/teamyapp/cloud/libs/env"
	"github.com/teamyapp/cloud/libs/gql"
	"github.com/teamyapp/cloud/libs/telemetry"
	"github.com/teamyapp/cloud/libs/transaction"
	api2 "github.com/teamyapp/teamy-backend/core/api"
	gql2 "github.com/teamyapp/teamy-backend/core/api/gql"
	"github.com/teamyapp/teamy-backend/core/cache"
	"github.com/teamyapp/teamy-backend/core/daov2"
	"github.com/teamyapp/teamy-backend/core/daov2/sqldb"
	"github.com/teamyapp/teamy-backend/core/feature"
	"github.com/teamyapp/teamy-backend/core/realtime"
	"github.com/teamyapp/teamy-backend/core/service"
)

// Injectors from wire.go:

func InitRealTimeStateSyncer(logger telemetry.Logger, sqlDB *sql.DB) *realtime.StateSyncer {
	factory := transaction.NewFactory(sqlDB)
	teamMember := sqldb.NewTeamMember(logger, factory)
	stateSyncer := realtime.NewStateSyncer(logger, teamMember)
	return stateSyncer
}

func InitGraphQLAPI(appName AppMame, serviceName ServiceName, environment env.Environment, logger telemetry.Logger, cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL, cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) (gql.Service[gql2.Resolver], error) {
	prometheusTracer := newPrometheusTracer(appName, serviceName, environment)
	authorizer := service.NewAuthorizer(logger, cloudAPIClientRegistry)
	toggles := feature.NewStaticToggles()
	factory := transaction.NewFactory(sqlDB)
	activity := cache.NewActivity(logger)
	task := sqldb.NewTask(logger, factory)
	thread := sqldb.NewThread(logger)
	sprint := sqldb.NewSprint(factory)
	taskAwaitForRelation := sqldb.NewTaskAwaitForRelation(logger)
	sprintParticipant := sqldb.NewSprintParticipant(logger, factory)
	sprintTaskRelation := sqldb.NewSprintTaskRelation(logger)
	serviceTask := service.NewTask(logger, cloudAPIClientRegistry, authorizer, toggles, realTimeStateSyncer, factory, activity, task, thread, sprint, taskAwaitForRelation, sprintParticipant, sprintTaskRelation)
	taskLink := sqldb.NewTaskLink(logger, sqlDB)
	serviceTaskLink := service.NewTaskLink(logger, cloudAPIClientRegistry, factory, authorizer, toggles, realTimeStateSyncer, taskLink, task)
	team := sqldb.NewTeam(logger, factory)
	teamMember := sqldb.NewTeamMember(logger, factory)
	teamFileUploadSession := sqldb.NewTeamFileUploadSession(logger)
	teamGroup := sqldb.NewTeamGroup(logger, factory)
	serviceTeam := newTeamService(logger, cloudWebAPIExternalBaseURL, cloudAPIClientRegistry, authorizer, toggles, realTimeStateSyncer, factory, task, sprint, sprintParticipant, team, teamMember, teamFileUploadSession, teamGroup)
	serviceSprint := service.NewSprint(logger, cloudAPIClientRegistry, realTimeStateSyncer, authorizer, toggles, factory, task, sprint, team, sprintTaskRelation, sprintParticipant, teamMember, thread)
	user := sqldb.NewUser(logger, factory)
	userFileUploadSession := sqldb.NewUserFileUploadSession(logger)
	serviceUser := newUserService(logger, cloudWebAPIExternalBaseURL, cloudAPIClientRegistry, realTimeStateSyncer, factory, toggles, user, teamMember, userFileUploadSession)
	invitation := sqldb.NewInvitation(logger, factory)
	serviceInvitation := service.NewInvitation(logger, cloudAPIClientRegistry, authorizer, toggles, realTimeStateSyncer, factory, invitation, teamMember, sprintParticipant, sprint)
	message := sqldb.NewMessage(logger, factory)
	serviceThread := service.NewThread(logger, cloudAPIClientRegistry, realTimeStateSyncer, factory, toggles, task, thread, message)
	app := sqldb.NewApp(logger, factory)
	appVersion := sqldb.NewAppVersion(logger, sqlDB)
	appTeamInstallation := sqldb.NewAppTeamInstallation(logger, sqlDB)
	appVersionVisibleTeam := sqldb.NewAppVersionVisibleTeam(logger)
	serviceApp := service.NewApp(logger, cloudAPIClientRegistry, authorizer, toggles, factory, realTimeStateSyncer, app, appVersion, appTeamInstallation, appVersionVisibleTeam, team)
	dependencies := gql2.NewDependencies(logger, serviceTask, serviceTaskLink, serviceTeam, serviceSprint, serviceUser, serviceInvitation, serviceThread, serviceApp)
	resolver := gql2.NewResolver(dependencies)
	gqlService := api2.NewGraphQL(logger, prometheusTracer, resolver)
	return gqlService, nil
}

func InitRealTimeStateSyncAPI(logger telemetry.Logger, realTimeStateSyncer *realtime.StateSyncer) api2.RealTimeStateSync {
	realTimeStateSync := api2.NewRealTimeStateSync(logger, realTimeStateSyncer)
	return realTimeStateSync
}

func InitTaskRPCAPI(logger telemetry.Logger, cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) api2.TaskRPC {
	authorizer := service.NewAuthorizer(logger, cloudAPIClientRegistry)
	toggles := feature.NewStaticToggles()
	factory := transaction.NewFactory(sqlDB)
	activity := cache.NewActivity(logger)
	task := sqldb.NewTask(logger, factory)
	thread := sqldb.NewThread(logger)
	sprint := sqldb.NewSprint(factory)
	taskAwaitForRelation := sqldb.NewTaskAwaitForRelation(logger)
	sprintParticipant := sqldb.NewSprintParticipant(logger, factory)
	sprintTaskRelation := sqldb.NewSprintTaskRelation(logger)
	serviceTask := service.NewTask(logger, cloudAPIClientRegistry, authorizer, toggles, realTimeStateSyncer, factory, activity, task, thread, sprint, taskAwaitForRelation, sprintParticipant, sprintTaskRelation)
	taskRPC := api2.NewTaskRPC(logger, serviceTask)
	return taskRPC
}

func InitSprintRPCAPI(logger telemetry.Logger, cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) api2.SprintRPC {
	authorizer := service.NewAuthorizer(logger, cloudAPIClientRegistry)
	toggles := feature.NewStaticToggles()
	factory := transaction.NewFactory(sqlDB)
	task := sqldb.NewTask(logger, factory)
	sprint := sqldb.NewSprint(factory)
	team := sqldb.NewTeam(logger, factory)
	sprintTaskRelation := sqldb.NewSprintTaskRelation(logger)
	sprintParticipant := sqldb.NewSprintParticipant(logger, factory)
	teamMember := sqldb.NewTeamMember(logger, factory)
	thread := sqldb.NewThread(logger)
	serviceSprint := service.NewSprint(logger, cloudAPIClientRegistry, realTimeStateSyncer, authorizer, toggles, factory, task, sprint, team, sprintTaskRelation, sprintParticipant, teamMember, thread)
	sprintRPC := api2.NewSprintRPC(logger, serviceSprint)
	return sprintRPC
}

func InitTaskLinkRPCAPI(logger telemetry.Logger, cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) api2.TaskLinkRPC {
	factory := transaction.NewFactory(sqlDB)
	authorizer := service.NewAuthorizer(logger, cloudAPIClientRegistry)
	toggles := feature.NewStaticToggles()
	taskLink := sqldb.NewTaskLink(logger, sqlDB)
	task := sqldb.NewTask(logger, factory)
	serviceTaskLink := service.NewTaskLink(logger, cloudAPIClientRegistry, factory, authorizer, toggles, realTimeStateSyncer, taskLink, task)
	taskLinkRPC := api2.NewTaskLinkRPC(logger, serviceTaskLink)
	return taskLinkRPC
}

// wire.go:

type AppMame string

type ServiceName string

type CloudWebAPIExternalBaseURL string

var daoSet = wire.NewSet(wire.Bind(new(daov2.Task), new(sqldb.Task)), wire.Bind(new(daov2.TaskLink), new(sqldb.TaskLink)), wire.Bind(new(daov2.TaskAwaitForRelation), new(sqldb.TaskAwaitForRelation)), wire.Bind(new(daov2.SprintParticipant), new(sqldb.SprintParticipant)), wire.Bind(new(daov2.Sprint), new(sqldb.Sprint)), wire.Bind(new(daov2.SprintTaskRelation), new(sqldb.SprintTaskRelation)), wire.Bind(new(daov2.Thread), new(sqldb.Thread)), wire.Bind(new(daov2.TeamMember), new(sqldb.TeamMember)), wire.Bind(new(daov2.TeamGroup), new(sqldb.TeamGroup)), wire.Bind(new(daov2.User), new(sqldb.User)), wire.Bind(new(daov2.UserFileUploadSession), new(sqldb.UserFileUploadSession)), wire.Bind(new(daov2.Team), new(sqldb.Team)), wire.Bind(new(daov2.TeamFileUploadSession), new(sqldb.TeamFileUploadSession)), wire.Bind(new(daov2.Invitation), new(sqldb.Invitation)), wire.Bind(new(daov2.Message), new(sqldb.Message)), wire.Bind(new(daov2.App), new(sqldb.App)), wire.Bind(new(daov2.AppVersion), new(sqldb.AppVersion)), wire.Bind(new(daov2.AppVersionVisibleTeam), new(sqldb.AppVersionVisibleTeam)), wire.Bind(new(daov2.AppTeamInstallation), new(sqldb.AppTeamInstallation)), sqldb.NewTask, sqldb.NewTaskLink, sqldb.NewTaskAwaitForRelation, sqldb.NewSprintParticipant, sqldb.NewSprint, sqldb.NewSprintTaskRelation, sqldb.NewThread, sqldb.NewTeamMember, sqldb.NewTeamGroup, sqldb.NewUser, sqldb.NewUserFileUploadSession, sqldb.NewTeam, sqldb.NewTeamFileUploadSession, sqldb.NewInvitation, sqldb.NewMessage, sqldb.NewApp, sqldb.NewAppVersion, sqldb.NewAppVersionVisibleTeam, sqldb.NewAppTeamInstallation)

var serviceSet = wire.NewSet(service.NewThread, service.NewTask, service.NewTaskLink, service.NewInvitation, newTeamService, service.NewSprint, newUserService, service.NewAuthorizer, service.NewApp)

func newUserService(
	logger telemetry.Logger,
	cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL,
	cloudClientRegistry *api.ClientRegistry,
	stateSyncer *realtime.StateSyncer,
	transactionFactory transaction.Factory,
	toggles feature.Toggles,
	userDaoV2 daov2.User,
	teamMemberV2 daov2.TeamMember,
	userFileUploadSessionDaoV2 daov2.UserFileUploadSession,
) service.User {
	return service.NewUser(
		logger,
		string(cloudWebAPIExternalBaseURL),
		cloudClientRegistry,
		stateSyncer,
		transactionFactory,
		toggles,
		userDaoV2,
		teamMemberV2,
		userFileUploadSessionDaoV2,
	)
}

func newTeamService(
	logger telemetry.Logger,
	cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL,
	cloudClientRegistry *api.ClientRegistry,
	authorizer service.Authorizer,
	toggles feature.Toggles,
	stateSyncer *realtime.StateSyncer,
	transactionFactory transaction.Factory,
	taskDaoV2 daov2.Task,
	sprintDaoV2 daov2.Sprint,
	sprintParticipantDaoV2 daov2.SprintParticipant,
	teamDaoV2 daov2.Team,
	teamMemberDaoV2 daov2.TeamMember,
	teamFileUploadSessionDaoV2 daov2.TeamFileUploadSession,
	teamGroupDaoV2 daov2.TeamGroup,
) service.Team {
	return service.NewTeam(
		logger,
		string(cloudWebAPIExternalBaseURL),
		cloudClientRegistry,
		authorizer,
		toggles,
		stateSyncer,
		transactionFactory,
		taskDaoV2,
		sprintDaoV2,
		sprintParticipantDaoV2,
		teamDaoV2,
		teamMemberDaoV2,
		teamFileUploadSessionDaoV2,
		teamGroupDaoV2)
}

func newPrometheusTracer(appMame AppMame, serviceName ServiceName, environment env.Environment) gql.PrometheusTracer {
	return gql.NewPrometheusTracer(string(appMame), string(serviceName), environment)
}
