// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/teamyapp/cloud/app/api"
	api2 "github.com/teamyapp/teamy-backend/core/api"
	"github.com/teamyapp/teamy-backend/core/api/gql"
	"github.com/teamyapp/teamy-backend/core/collection"
	"github.com/teamyapp/teamy-backend/core/dao"
	"github.com/teamyapp/teamy-backend/core/dao/sqldb"
	"github.com/teamyapp/teamy-backend/core/realtime"
	"github.com/teamyapp/teamy-backend/core/service"
)

// Injectors from wire.go:

func InitRealTimeStateSyncer(sqlDB *sql.DB) *realtime.StateSyncer {
	teamMember := sqldb.NewTeamMember(sqlDB)
	stateSyncer := realtime.NewStateSyncer(teamMember)
	return stateSyncer
}

func InitGraphQLAPI(cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL, cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) (api2.GraphQL, error) {
	user := sqldb.NewUser(sqlDB)
	team := sqldb.NewTeam(sqlDB)
	teamMember := sqldb.NewTeamMember(sqlDB)
	invitation := sqldb.NewInvitation(sqlDB)
	message := sqldb.NewMessage(sqlDB)
	taskAwaitForRelation := sqldb.NewTaskAwaitForRelation(sqlDB)
	userSyncer := collection.NewUserSyncer(realTimeStateSyncer, user, teamMember)
	teamSyncer := collection.NewTeamSyncer(realTimeStateSyncer, team)
	teamMemberSyncer := collection.NewTeamMemberSyncer(realTimeStateSyncer, teamMember)
	invitationSyncer := collection.NewInvitationSyncer(realTimeStateSyncer, invitation)
	task := sqldb.NewTask(sqlDB)
	messageSyncer := collection.NewMessageSyncer(realTimeStateSyncer, message, task)
	taskAwaitForRelationSyncer := collection.NewTaskAwaitForRelationSyncer(realTimeStateSyncer, taskAwaitForRelation, task)
	thread := sqldb.NewThread(sqlDB)
	taskSyncer := collection.NewTaskSyncer(realTimeStateSyncer, task)
	serviceThread := service.NewThread(cloudAPIClientRegistry, thread)
	serviceTask := service.NewTask(cloudAPIClientRegistry, task, thread, taskAwaitForRelation, taskSyncer, taskAwaitForRelationSyncer, serviceThread)
	sprint := sqldb.NewSprint(sqlDB)
	teamFileUploadSession := sqldb.NewTeamFileUploadSession(sqlDB)
	serviceTeam := newTeamService(cloudWebAPIExternalBaseURL, cloudAPIClientRegistry, task, sprint, team, teamFileUploadSession)
	sprintTaskRelation := sqldb.NewSprintTaskRelation(sqlDB)
	serviceSprint := service.NewSprint(cloudAPIClientRegistry, task, sprint, sprintTaskRelation, sqlDB)
	userFileUploadSession := sqldb.NewUserFileUploadSession(sqlDB)
	serviceUser := newUserService(cloudWebAPIExternalBaseURL, cloudAPIClientRegistry, user, userFileUploadSession)
	dependencies := gql.NewDependencies(cloudAPIClientRegistry, user, team, teamMember, invitation, message, taskAwaitForRelation, userSyncer, teamSyncer, teamMemberSyncer, invitationSyncer, messageSyncer, taskAwaitForRelationSyncer, serviceTask, serviceTeam, serviceSprint, serviceUser)
	resolver := gql.NewResolver(dependencies)
	graphQL := api2.NewGraphQL(resolver)
	return graphQL, nil
}

func InitRealTimeStateSyncAPI(realTimeStateSyncer *realtime.StateSyncer) api2.RealTimeStateSync {
	realTimeStateSync := api2.NewRealTimeStateSync(realTimeStateSyncer)
	return realTimeStateSync
}

func InitTaskRPCAPI(cloudAPIClientRegistry *api.ClientRegistry, realTimeStateSyncer *realtime.StateSyncer, sqlDB *sql.DB) api2.TaskRPC {
	task := sqldb.NewTask(sqlDB)
	thread := sqldb.NewThread(sqlDB)
	taskAwaitForRelation := sqldb.NewTaskAwaitForRelation(sqlDB)
	taskSyncer := collection.NewTaskSyncer(realTimeStateSyncer, task)
	taskAwaitForRelationSyncer := collection.NewTaskAwaitForRelationSyncer(realTimeStateSyncer, taskAwaitForRelation, task)
	serviceThread := service.NewThread(cloudAPIClientRegistry, thread)
	serviceTask := service.NewTask(cloudAPIClientRegistry, task, thread, taskAwaitForRelation, taskSyncer, taskAwaitForRelationSyncer, serviceThread)
	taskRPC := api2.NewTaskRPC(serviceTask)
	return taskRPC
}

func InitSprintRPCAPI(cloudAPIClientRegistry *api.ClientRegistry, sqlDB *sql.DB) api2.SprintRPC {
	task := sqldb.NewTask(sqlDB)
	sprint := sqldb.NewSprint(sqlDB)
	sprintTaskRelation := sqldb.NewSprintTaskRelation(sqlDB)
	serviceSprint := service.NewSprint(cloudAPIClientRegistry, task, sprint, sprintTaskRelation, sqlDB)
	sprintRPC := api2.NewSprintRPC(serviceSprint)
	return sprintRPC
}

// wire.go:

type CloudWebAPIExternalBaseURL string

var daoSet = wire.NewSet(wire.Bind(new(dao.Invitation), new(sqldb.Invitation)), wire.Bind(new(dao.Message), new(sqldb.Message)), wire.Bind(new(dao.Task), new(sqldb.Task)), wire.Bind(new(dao.Team), new(sqldb.Team)), wire.Bind(new(dao.TeamMember), new(sqldb.TeamMember)), wire.Bind(new(dao.User), new(sqldb.User)), wire.Bind(new(dao.Thread), new(sqldb.Thread)), wire.Bind(new(dao.Sprint), new(sqldb.Sprint)), wire.Bind(new(dao.TaskAwaitForRelation), new(sqldb.TaskAwaitForRelation)), wire.Bind(new(dao.SprintTaskRelation), new(sqldb.SprintTaskRelation)), wire.Bind(new(dao.UserFileUploadSession), new(sqldb.UserFileUploadSession)), wire.Bind(new(dao.TeamFileUploadSession), new(sqldb.TeamFileUploadSession)), sqldb.NewInvitation, sqldb.NewMessage, sqldb.NewTask, sqldb.NewTeam, sqldb.NewTeamMember, sqldb.NewUser, sqldb.NewThread, sqldb.NewSprint, sqldb.NewTaskAwaitForRelation, sqldb.NewSprintTaskRelation, sqldb.NewUserFileUploadSession, sqldb.NewTeamFileUploadSession)

var collectionSyncerSet = wire.NewSet(collection.NewInvitationSyncer, collection.NewMessageSyncer, collection.NewTaskSyncer, collection.NewTaskAwaitForRelationSyncer, collection.NewTeamSyncer, collection.NewTeamMemberSyncer, collection.NewUserSyncer)

var serviceSet = wire.NewSet(service.NewThread, service.NewTask, newTeamService, service.NewSprint, newUserService)

func newUserService(
	cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL,
	cloudClientRegistry *api.ClientRegistry,
	userDao dao.User,
	userFileUploadSessionDao dao.UserFileUploadSession,
) service.User {
	return service.NewUser(string(cloudWebAPIExternalBaseURL), cloudClientRegistry, userDao, userFileUploadSessionDao)
}

func newTeamService(
	cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL,
	cloudClientRegistry *api.ClientRegistry,
	taskDao dao.Task,
	sprintDao dao.Sprint,
	teamDao dao.Team,
	teamFileUploadSessionDao dao.TeamFileUploadSession,
) service.Team {
	return service.NewTeam(string(cloudWebAPIExternalBaseURL), cloudClientRegistry, taskDao, sprintDao, teamDao, teamFileUploadSessionDao)
}
