apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: teamy-backend
  labels:
    app: teamy-backend
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: teamy-backend
  template:
    metadata:
      labels:
        app: teamy-backend
    spec:
      containers:
        - name: teamy-backend
          image: harbor.internal.teamyapp.com/internal/teamy-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
      imagePullSecrets:
        - name: harbor-cred
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: teamy-backend
spec:
  selector:
    app: teamy-backend
  ports:
    - name: http
      port: 80
      targetPort: 9000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: production
  name: teamy-backend
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`teamy-backend.teamyapp.com`)
      services:
        - kind: Service
          name: teamy-backend
          namespace: production
          port: 80
          passHostHeader: true
  tls:
    secretName: teamy-cert

