apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: template-go
  labels:
    app: template-go
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: template-go
  template:
    metadata:
      labels:
        app: template-go
    spec:
      containers:
        - name: template-go
          image: harbor.internal.teamyapp.com/internal/template-go:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: harbor-cred
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: template-go
spec:
  selector:
    app: template-go
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: production
  name: template-go
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`template-go.teamyapp.com`)
      services:
        - kind: Service
          name: template-go
          namespace: production
          port: 80
          passHostHeader: true
  tls:
    secretName: teamy-cert

