apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  namespace: production
  name: teamy
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secrets-read-role
  data:
    - name: user
      key: kv/data/secrets/db/postgres/teamy/prod
      property: user
    - name: password
      key: kv/data/secrets/db/postgres/teamy/prod
      property: password
    - name: db-name
      key: kv/data/secrets/db/postgres/teamy/prod
      property: db-name
    - name: service-account-api-token
      key: kv/data/secrets/production/teamy
      property: service-account-api-token
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  namespace: production
  name: apps
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secrets-read-role
  data:
    - name: github-webhook-secret
      key: kv/data/secrets/production/apps
      property: github-webhook-secret
    - name: service-account-api-token
      key: kv/data/secrets/production/apps
      property: service-account-api-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: teamy-backend
  labels:
    app: teamy-backend
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: teamy-backend
  template:
    metadata:
      labels:
        app: teamy-backend
    spec:
      containers:
        - name: teamy-backend
          image: registry.digitalocean.com/teamyapp/teamy-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: DB_HOST
              value: postgres.db.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: db-name
            - name: CLOUD_WEB_API_EXTERNAL_BASE_URL
              value: https://cloud.teamyapp.com
            - name: CLOUD_WEB_API_BASE_URL
              value: http://cloud
            - name: CLOUD_GRPC_API_HOST
              value: cloud
            - name: CLOUD_GRPC_API_PORT
              value: "81"
            - name: CLOUD_GRPC_API_SHOULD_ENCRYPT
              value: "false"
            - name: SERVICE_RUNNER_WEB_SERVER_PORT
              value: "9000"
            - name: SERVICE_RUNNER_GRPC_SERVER_PORT
              value: "9001"
            - name: SERVICE_RUNNER_IDENTITY_API_ENDPOINT
              value: http://cloud/identity
            - name: APPS_GITHUB_APP_NAME
              value: teamy-apps
            - name: APPS_GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: github-webhook-secret
            - name: APPS_SERVICE_ACCOUNT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: service-account-api-token
            - name: TEAMY_SERVICE_ACCOUNT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: service-account-api-token
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: teamy-backend
spec:
  selector:
    app: teamy-backend
  ports:
    - name: web-services
      port: 9000
    - name: rpc-services
      port: 9001
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: production
  name: teamy-backend
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`web-backend.teamyapp.com`)
      services:
        - kind: Service
          name: teamy-backend
          namespace: production
          port: 9000
          passHostHeader: true
    - kind: Rule
      match: Host(`rpc-backend.teamyapp.com`)
      services:
        - kind: Service
          name: teamy-backend
          namespace: production
          port: 9001
          passHostHeader: true
          scheme: h2c
  tls:
    secretName: teamy-cert

