apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  namespace: staging
  name: teamy
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secrets-read-role
  data:
    - name: user
      key: kv/data/secrets/db/postgres/teamy/staging
      property: user
    - name: password
      key: kv/data/secrets/db/postgres/teamy/staging
      property: password
    - name: db-name
      key: kv/data/secrets/db/postgres/teamy/staging
      property: db-name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: teamy-backend
  labels:
    app: teamy-backend
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: teamy-backend
  template:
    metadata:
      labels:
        app: teamy-backend
    spec:
      containers:
        - name: teamy-backend
          image: registry.digitalocean.com/teamyapp/teamy-backend-staging:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: postgres.db.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: db-name
            - name: IDENTITY_API_ENDPOINT
              value: http://cloud.staging.svc.cluster.local/identity
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: teamy-backend
spec:
  selector:
    app: teamy-backend
  ports:
    - name: http
      port: 80
      targetPort: 9000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: staging
  name: teamy-backend
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`backend.staging.teamyapp.com`)
      services:
        - kind: Service
          name: teamy-backend
          namespace: staging
          port: 80
          passHostHeader: true
  tls:
    secretName: teamy-cert
