apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  namespace: testing
  name: teamy
spec:
  itemPath: vaults/Automation/items/apps:testing:teamy
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  namespace: testing
  name: apps
spec:
  itemPath: vaults/Automation/items/apps:testing:apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testing
  name: teamy-backend
  labels:
    app: teamy-backend
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: teamy-backend
  template:
    metadata:
      labels:
        app: teamy-backend
    spec:
      containers:
        - name: teamy-backend
          image: registry.digitalocean.com/teamyapp/teamy-backend-testing:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
            - containerPort: 9001
            - containerPort: 10000
            - containerPort: 10001
          env:
            - name: ENVIRONMENT
              value: testing
            - name: DB_HOST
              value: postgres.db.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: db-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: db-name
            - name: DB_MAX_OPEN_CONNECTIONS
              value: "150"
            - name: DB_MAX_IDLE_CONNECTIONS
              value: "15"
            - name: DB_CONNECTION_MAX_LIFE_TIME
              value: "30m"
            - name: DB_CONNECTION_MAX_IDLE_TIME
              value: "30m"
            - name: CLOUD_WEB_API_EXTERNAL_BASE_URL
              value: https://cloud.testing.teamyapp.com
            - name: CLOUD_WEB_API_BASE_URL
              value: http://cloud
            - name: CLOUD_GRPC_API_HOST
              value: cloud
            - name: CLOUD_GRPC_API_PORT
              value: "81"
            - name: CLOUD_GRPC_API_SHOULD_ENCRYPT
              value: "false"
            - name: CACHE_CAPACITY
              value: "100000"
            - name: TIME_BASED_CACHE_BUCKET_COUNT
              value: "1000"
            - name: TIME_BASED_CACHE_TTL
              value: "120s"
            - name: REQUEST_RETRY_MAX_COUNT # Temporary set to 1 before error category is implemented
              value: "1"
            - name: SERVICE_RUNNER_WEB_SERVER_PORT
              value: "9000"
            - name: SERVICE_RUNNER_GRPC_SERVER_PORT
              value: "9001"
            - name: SERVICE_RUNNER_MONITORING_SERVER_PORT
              value: "10000"
            - name: SERVICE_RUNNER_ENABLE_TRACING
              value: "true"
            - name: SERVICE_RUNNER_TRACE_COLLECTOR_ENDPOINT
              value: "tempo.monitoring:4317"
            - name: SERVICE_RUNNER_IDENTITY_API_ENDPOINT
              value: http://cloud/identity
            - name: APPS_GITHUB_APP_NAME
              value: teamy-apps-testing
            - name: APPS_GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: github-app-id
            - name: APPS_GITHUB_PRIVATE_KEY_PEM_FILE_PATH
              value: /var/lib/vault/github/private-key.pem
            - name: APPS_GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: github-webhook-secret
            - name: APPS_SERVICE_ACCOUNT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apps
                  key: internal-service-account-api-token
            - name: TEAMY_SERVICE_ACCOUNT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: internal-service-account-api-token
            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: teamy
                  key: jwt-signing-key
            - name: TEAMY_WEB_UI_BASE_URL
              value: "https://testing.teamyapp.com"
          volumeMounts:
            - mountPath: /var/lib/vault
              name: vault
      volumes:
        - name: vault
          secret:
            secretName: apps
            defaultMode: 0600
            items:
              - key: github-private-key.pem
                path: github/private-key.pem
---
apiVersion: v1
kind: Service
metadata:
  namespace: testing
  name: teamy-backend
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '10000'
spec:
  selector:
    app: teamy-backend
  ports:
    - name: web
      port: 9000
    - name: rpc
      port: 9001
    - name: monitoring
      port: 10000
    - name: profiling
      port: 10001
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: testing
  name: teamy-backend
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`web-backend.testing.teamyapp.com`)
      services:
        - kind: Service
          name: teamy-backend
          namespace: testing
          port: 9000
          passHostHeader: true
    - kind: Rule
      match: Host(`rpc-backend.testing.teamyapp.com`)
      services:
        - kind: Service
          name: teamy-backend
          namespace: testing
          port: 9001
          passHostHeader: true
          scheme: h2c
  tls:
    secretName: cert-teamyapp.com

