schema {
	query: Query
	mutation: Mutation
}

type Query {
	me: User!
	tasks(filter: TaskFilter): [Task!]!
	teams(filter: TeamFilter): [Team!]!
	invitations(filter: InvitationFilter): [Invitation!]!
	sprints(filter: SprintFilter): [Sprint!]!
	apps(filter: AppFilter): [App!]!
}

type Mutation {
	# Task
	createTask(teamId: ID!, task: CreateTaskInput!): Task!
	updateTask(taskId: ID!, input: UpdateTaskInput!): Task!
	deleteTask(taskId: ID!): Task!
	moveTaskToUpcoming(taskId: ID!): Task!
	moveTaskToInProgress(taskId: ID!): Task!
	moveTaskToDelivered(taskId: ID!): Task!
	moveTaskToBlocked(taskId: ID!, reason: String!): Task!
	addAwaitForTask(taskId: ID!, awaitForTaskId: ID!): Task!
	removeAwaitForTask(taskId: ID!, awaitForTaskId: ID!): Task!
	startDraggingTask(taskId: ID!, clientId: ID!): ID!
	stopDraggingTask(taskId: ID!, clientId: ID!): ID!

	# Message
	createMessage(threadId: ID!, message: CreateMessageInput!): Message!
	updateMessage(messageId: ID!, input: UpdateMessageInput!): Message!
	deleteMessage(messageId: ID!): Message!

	# Team
	createTeam(team: CreateTeamInput!): Team!
	updateTeam(teamId: ID!, input: UpdateTeamInput!): Team!
	createTeamIconUploadSession(teamId: ID!): ID!
	finishTeamIconUploadSession(teamId: ID!, fileUploadSessionId: ID!): Team!
	addMemberToTeam(teamId: ID!, memberUserId: ID!): TeamMember!
	updateTeamMember(teamId: ID!, input: UpdateTeamMemberInput!): TeamMember!
	removeMemberFromTeam(teamId: ID!, memberUserId: ID!): TeamMember!

	# User
	createUser(user: CreateUserInput!): User!
	updateUser(userId: ID!, input: UpdateUserInput!): User!
	createUserProfileUploadSession: ID!
	finishUserProfileUploadSession(fileUploadSessionId: ID!): User!

	# Invitation
	createInvitation(
		teamId: ID!
		invitation: CreateInvitationInput!
	): Invitation!
	updateInvitation(
		invitationId: ID!
		input: UpdateInvitationInput!
	): Invitation!
	acceptInvitation(invitationId: ID!, invitationCode: String!): Invitation!
	declineInvitation(invitationId: ID!, invitationCode: String!): Invitation!
	deleteInvitation(invitationId: ID!): Invitation!

	# Sprint
	createSprint(teamId: ID!, sprint: CreateSprintInput!): Sprint!
	deleteSprint(sprintId: ID!): Sprint!
	addTaskToSprint(sprintId: ID!, taskId: ID!): Task!
	moveTasksToSprint(
		fromSprintId: ID!
		toSprintId: ID!
		taskIds: [ID!]!
	): [Task!]!
	copyTasksToSprint(
		toSprintId: ID!
		taskIds: [ID!]!
	): [Task!]!
	removeTaskFromSprint(sprintId: ID!, taskId: ID!): Task!

	# File
	createFileUploadSession(teamId: ID!): ID!
	finishFileUploadSession(teamId: ID!): FileMetadata!
	updateFileMetadata(fileId: ID!, input: FileMetadataInput!): FileMetadata!
	deleteFile(fileId: ID!): FileMetadata!

	# App
	createApp: App!
	updateApp(input: UpdateAppInput!): App!
	deleteApp(appId: ID!): App!
	refreshAppSecret: App!
	createAppVersion(appId: ID!): AppVersion!
	updateAppVersion(appId: ID!, input: UpdateAppVersionInput!): AppVersion!
	deleteAppVersion(appId: ID!, versionNumber: Int!): AppVersion!
	addVisibleTeamToAppVersion(
		appId: ID!
		versionNumber: Int!
		teamId: ID!
	): AppVersion!
	removeVisibleTeamFromAppVersion(
		appId: ID!
		versionNumber: Int!
		teamId: ID!
	): AppVersion!
}

scalar Duration

scalar Time

type Task {
	id: ID!
	goal: String!
	context: String
	creator: User!
	owner: User
	owningTeam: Team!
	status: TaskStatus!
	isPlanned: Boolean!
	comments: Thread!
	createdAt: Time!
	updatedAt: Time
	deliveredAt: Time
	dueAt: Time
	effort: Duration
	availableActions: [TaskAction!]!
	awaitForTasks: [Task!]!
}

type Message {
	id: ID!
	body: String!
	author: User!
	thread: Thread!
	createdAt: Time!
	updatedAt: Time
}

type Thread {
	id: ID!
	messages: [Message!]!
}

type Sprint {
	id: ID!
	startAt: Time!
	endAt: Time!
	owningTeam: Team!
	tasks(filter: TaskFilter): [Task!]!
	createdAt: Time!
	participants: [SprintParticipant!]!
}

type SprintParticipant {
	sprint: Sprint!
	user: User!
	totalBandwidth: Duration!
	unusedBandwidth: Duration!
	createdAt: Time!
	updatedAt: Time
}

type Team {
	id: ID!
	name: String!
	iconUrl: String
	createdAt: Time!
	creator: User!
	owner: User!
	members: [TeamMember!]!
	tasks(filter: TaskFilter): [Task!]!
	invitations(filter: InvitationFilter): [Invitation!]!
	sprints(filter: SprintFilter): [Sprint!]!
	appInstallations: [AppInstallation!]!
	taskActivities: [TaskActivity!]!
}

type TeamMember {
	team: Team!
	user: User!
	weeklyBandwidth: Duration!
	createdAt: Time!
	updatedAt: Time
}

type TaskActivity {
	taskId: ID!
	dragTaskActivity: DragTaskActivity!
}

type DragTaskActivity {
	isDragging: Boolean!
	client: Client
}

type Client {
	id: ID!
	user: User!
}

type Invitation {
	id: ID!
	sender: User!
	receiverFirstName: String
	receiverLastName: String
	receiverEmail: String
	receiver: User
	joiningTeam: Team!
	expireAt: Time!
	createdAt: Time!
	updatedAt: Time
	status: InvitationStatus!
	code: String!
}

type FileMetadata {
	id: ID!
	name: String!
	createdAt: Time!
	lastModifiedAt: Time
	owningTeam: Team!
}

enum InvitationStatus {
	PENDING
	ACCEPTED
	DECLINED
	EXPIRED
}

enum TaskAction {
	START
	DELETE
	ASSIGN_OWNER
	REPORT_BLOCKED
	MARK_COMPLETE
}

enum TaskStatus {
	TODO
	IN_PROGRESS
	PAUSED
	AWAITING
	BLOCK
	DELIVERED
}

type User {
	id: ID!
	firstName: String!
	lastName: String!
	profileUrl: String
	createdAt: Time!
	updatedAt: Time
	teams(filter: TeamFilter): [Team!]!
}

type App {
	id: ID!
	apiSecret: String!
	activeVersion: AppVersion
	versions: [AppVersion!]!
	installations: [AppInstallation!]!
	installationCount: Int!
	creator: User!
	createdAt: Time!
	updatedAt: Time
}

type AppVersion {
	app: App!
	versionNumber: Int!
	appName: String!
	iconUrl: String
	hasUiExtension: Boolean!
	uiExtensionEntrypointPath: String
	isPublic: Boolean!
	visibleToTeams: [Team!]!
	createdAt: Time!
	updatedAt: Time
}

type AppInstallation {
	id: ID!
	app: App!
	installedTeam: Team!
	installedBy: User!
	installedAt: Time!
}

# Filters
input TaskFilter {
	taskId: ID
	ownerId: ID
	goalContains: String
	status: TaskStatus
	isPlanned: Boolean
}

input TeamFilter {
	teamId: ID
}

input InvitationFilter {
	invitationId: ID
	code: String
}

input SprintFilter {
	sprintId: ID
	startAtAndAfter: Time
	sortByStartAt: Boolean
	countLimit: Int
}

input AppFilter {
	isPublic: Boolean
}

# Inputs
input CreateTaskInput {
	goal: String!
	context: String
	ownerUserId: ID
	dueAt: Time
	isPlanned: Boolean
}

input UpdateTaskInput {
	goal: String!
	context: String
	ownerUserId: ID
	owningTeamId: ID!
	effort: Duration
	dueAt: Time
}

input CreateMessageInput {
	body: String!
}

input UpdateMessageInput {
	body: String!
}

input CreateTeamInput {
	name: String!
}

input UpdateTeamInput {
	name: String!
	ownerUserId: ID!
}

input UpdateTeamMemberInput {
	userId: ID!
	weeklyBandwidth: Duration!
}

input CreateUserInput {
	lastName: String!
	firstName: String!
	profileUrl: String
}

input UpdateUserInput {
	lastName: String!
	firstName: String!
}

input CreateInvitationInput {
	receiverFirstName: String
	receiverLastName: String
	receiverEmail: String
	expireAt: Time!
}

input UpdateInvitationInput {
	receiverFirstName: String
	receiverLastName: String
	expireAt: Time!
}

input CreateSprintInput {
	startAt: Time!
	endAt: Time!
}

input FileMetadataInput {
	name: String!
}

input UpdateAppInput {
	activeVersionNumber: Int
}

input UpdateAppVersionInput {
	versionNumber: Int!
	name: String!
	iconUrl: String
	hasUiExtension: Boolean!
	uiExtensionEntryPointPath: String
	isPublic: Boolean!
}
