#!/bin/bash

GIT_LONG_COMMIT_HASH=$(git rev-parse HEAD)
GIT_REPO_OWNER=teamyapp
GIT_REPO_NAME=teamy-backend

cat > .repo.env <<EOF
GIT_LONG_COMMIT_HASH=$GIT_LONG_COMMIT_HASH
GIT_REPO_OWNER=$GIT_REPO_OWNER
GIT_REPO_NAME=$GIT_REPO_NAME
EOF

cat .repo.env
