[[target]]
name = "wireGen"
type = "goWire"
src = [
    "wire.go",
]

[[target]]
name = "dep"
type = "goLibrary"
dep = [
	"(@):module",
    ":wireGen",
	"(github.com/google/wire)",
	"(@)/app/repo",
	"(@)/app/service"
]
