// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"

	"github.com/google/wire"
	"github.com/teamyapp/teamy-backend/app/api/gql/datastore"
	"github.com/teamyapp/teamy-backend/app/api/gql/resolver"
	resolver2 "github.com/teamyapp/teamy-backend/app/api/gqlv2/resolver"
	"github.com/teamyapp/teamy-backend/app/dao"
	"github.com/teamyapp/teamy-backend/app/dao/sqldb"
	"github.com/teamyapp/teamy-backend/app/repo"
	"github.com/teamyapp/teamy-backend/app/service"
)

// Injectors from wire.go:

func InitGraphQLResolver(sqlDB *sql.DB) resolver.Resolver {
	sqlTeam := repo.NewSQLTeam(sqlDB)
	prioritization := service.NewPrioritization()
	postgresPersister := datastore.NewPostgresPersister(sqlDB)
	dataStore := datastore.NewDataStore(postgresPersister)
	dependencies := resolver.NewDependencies(sqlTeam, prioritization, dataStore)
	resolverResolver := resolver.NewResolver(dependencies)
	return resolverResolver
}

func InitGraphQLV2Resolver(sqlDB *sql.DB) resolver2.Resolver {
	user := sqldb.NewUser(sqlDB)
	team := sqldb.NewTeam(sqlDB)
	teamMember := sqldb.NewTeamMember(sqlDB)
	invitation := sqldb.NewInvitation(sqlDB)
	task := sqldb.NewTask(sqlDB)
	message := sqldb.NewMessage(sqlDB)
	dependencies := resolver2.NewDependencies(user, team, teamMember, invitation, task, message)
	resolverResolver := resolver2.NewResolver(dependencies)
	return resolverResolver
}

// wire.go:

var repoSet = wire.NewSet(wire.Bind(new(repo.Team), new(repo.SQLTeam)), wire.Bind(new(repo.Task), new(repo.SQLTask)), wire.Bind(new(repo.User), new(repo.SQLUser)), repo.NewSQLTeam, repo.NewSQLTask, repo.NewSQLUser)

var daoSet = wire.NewSet(wire.Bind(new(dao.Invitation), new(sqldb.Invitation)), wire.Bind(new(dao.Message), new(sqldb.Message)), wire.Bind(new(dao.Task), new(sqldb.Task)), wire.Bind(new(dao.Team), new(sqldb.Team)), wire.Bind(new(dao.TeamMember), new(sqldb.TeamMember)), wire.Bind(new(dao.User), new(sqldb.User)), sqldb.NewInvitation, sqldb.NewMessage, sqldb.NewTask, sqldb.NewTeam, sqldb.NewTeamMember, sqldb.NewUser)
