// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dep

import (
	"database/sql"

	"github.com/google/wire"
	"github.com/teamyapp/teamy-backend/app/api/gql/resolver"
	"github.com/teamyapp/teamy-backend/app/repo"
	"github.com/teamyapp/teamy-backend/app/service"
)

// Injectors from wire.go:

func InitGraphQLResolver(sqlDB *sql.DB) resolver.Resolver {
	sqlTask := repo.NewSQLTask(sqlDB)
	task := service.NewTask(sqlTask)
	sqlTeam := repo.NewSQLTeam(sqlDB)
	team := service.NewTeam(sqlTeam)
	prioritization := service.NewPrioritization()
	execution := service.NewExecution(team, prioritization, sqlTask)
	resolverResolver := resolver.NewResolver(task, execution)
	return resolverResolver
}

// wire.go:

var repoSet = wire.NewSet(wire.Bind(new(repo.Team), new(repo.SQLTeam)), wire.Bind(new(repo.Task), new(repo.SQLTask)), repo.NewSQLTeam, repo.NewSQLTask)
