// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/teamyapp/teamy-backend/app/api/gql/resolver"
	resolver2 "github.com/teamyapp/teamy-backend/app/api/gqlv2/resolver"
	"github.com/teamyapp/teamy-backend/app/repo"
	"github.com/teamyapp/teamy-backend/app/service"
)

// Injectors from wire.go:

func InitGraphQLResolver(sqlDB *sql.DB) resolver.Resolver {
	sqlUser := repo.NewSQLUser(sqlDB)
	sqlTask := repo.NewSQLTask(sqlDB)
	sqlTeam := repo.NewSQLTeam(sqlDB)
	prioritization := service.NewPrioritization()
	dependencies := resolver.NewDependencies(sqlUser, sqlTask, sqlTeam, prioritization)
	postgresPersister := resolver2.NewPostgresPersister(sqlDB)
	dataStore := resolver2.NewDataStore(postgresPersister)
	resolverDependencies := resolver2.NewDependencies(dataStore)
	resolverResolver := resolver.NewResolver(dependencies, resolverDependencies)
	return resolverResolver
}

// wire.go:

var repoSet = wire.NewSet(wire.Bind(new(repo.Team), new(repo.SQLTeam)), wire.Bind(new(repo.Task), new(repo.SQLTask)), wire.Bind(new(repo.User), new(repo.SQLUser)), repo.NewSQLTeam, repo.NewSQLTask, repo.NewSQLUser)
