query GetAllMyData {
  me {
    teams {
      id
      name
    }
    activeTeam {
      id
      name
      tasks {
        ...TaskDetails
      }
    }
    tasks {
      ...TaskDetails
    }
  }
}

query GetTask($id: ID!) {
  task(id: $id) {
    ...TaskDetails
  }
}

query MyActiveTeam {
  me {
    activeTeam {
      id
      name
      tasks {
        ...TaskDetails
      }
    }
  }
}

fragment TaskDetails on Task {
  id
  goal
  context
  creator {
    id
    lastName
    firstName
  }
  owner {
    id
    lastName
    firstName
  }
  comments {
    id
    content
    commenter {
      id
      lastName
      firstName
    }
  }
}
