name: Feature
on:
  pull_request:
    branches:
      - master
    types: [synchronize]
env:
  GOPRIVATE: github.com/teamyapp
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: |
          go env -w GOPRIVATE
          go env -w GONOPROXY
          go env -w GONOSUMDB
          go mod download
      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
